### ISSUE TITLE
Sentry picking up the wrong variable to set the 'environment' tag

### ISSUE THREAD

**Issue by jmooo** [getsentry/sentry-java#1057]
_Platform:_
Spring 2.3.1.RELEASE
Sentry SDK (via maven) 1.7.30

---
Sentry is picking up `SPRING_PROFILES_ACTIVE` instead of `SENTRY_ENVIRONMENT` for setting the `environment` tag

**Steps to reproduce:**
Create env vars for your java app:
`SPRING_PROFILES_ACTIVE=profile1,profile2`
`SENTRY_ENVIRONMENT=prod`

Restart the app and trigger an error

**Actual result:**
`environment` tag inside the Sentry dashboard is set to `profile1,profile2`

**Expected result:**
`environment` tag should be `prod`

My `sentry.properties` file contains no reference to `environment`, that field is only ever set via an env var. Similarly my `application.yaml` does not have a `sentry.environment` config setting. Though even if it did from my understanding in Spring an env var should take precedence over any other method.

**Comment by marandaneto** [comment]
@jmooo thanks for raising this.

so the precedence order is defined here https://github.com/getsentry/sentry-java/blob/4a9b3cc961e74421b8c56b77cc4808c5ddae2d5b/sentry/src/main/java/io/sentry/config/PropertiesProviderFactory.java#L14-L29

I don't see how it could be reading from `SPRING_PROFILES_ACTIVE` instead of `SENTRY_ENVIRONMENT`, but please double-check if you don't have the `environment` field defined somewhere in the supported properties resolution.

I'd bet that you have this defined somewhere, let us know your findings :)

**Comment by maciejwalkowiak** [comment]
SDK does not read `SPRING_PROFILES_ACTIVE` property. If you have an overlap between what you set there and the `environment` property on Sentry events, it means that you have somewhere a bug where you set the environment variables.

Just to make sure I've run a sample with these two environment variables and the `environment` property is set as expected.

**Comment by jmooo** [comment]
You tested with the versions I mentioned? No matter what I set the env var values to, only the value of `SPRING_PROFILES_ACTIVE` is ever logged to Sentry

The env vars systemd provides to the spring-boot app:

```
SENTRY_ENVIRONMENT=real_env
SPRING_PROFILES_ACTIVE=fake_env
SENTRY_DSN=https://my.dsn.here```

**Comment by maciejwalkowiak** [comment]
My apologies now i realized its about Sentry SDk 1.7. please considering updating to 3.x
