### ISSUE TITLE
Java Server Transport

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1097]
The goal is to have a transport with high transaction throughput.

### Constraints and requirements:

* Not required by Android
* Doesn't require offline caching
* Flushed data doesn't need to be sent in order
* Measure from baseline each change as we experiment
* Metrics on dropped items. i.e: Atomic increment for dropped items so we have visibility

### Some ideas:

* Parallelize envelope serialization
* Maintain N concurrent open connections
* Producer/Consumer `Envelope` to `Requests` 
  * `Requests` are gzip compressed blobs ready for the network I/O
* To test it out: [Benchmarks](https://www.baeldung.com/java-microbenchmark-harness) with a fake HTTP simulating a 1ms latency.

**Comment by maciejwalkowiak** [comment]
The biggest factor is not serialization but opening HTTP connection and waiting for the result. Ideally we would make `Connection#send` return `Future<Void>` instead of `void` but this would mean we need to change also the `Sentry` API which I believe is not desirable. 

I'll continue investigating with the approach of speeding up HTTP client and see how far it takes me.

**Comment by maciejwalkowiak** [comment]
Switching to non blocking version solves the problem completely BUT as a drawback - pulls dependencies to HTTP clients that users may not want to have on their classpath. I believe the right way to continue is to give users an easy way to provide their own instance of `Connection` so that they can implement sending data to Sentry using the client of their choice. 

In addition to that, we will provide one NIO based implementation - based either on 
- https://github.com/AsyncHttpClient/async-http-client or
- https://hc.apache.org/httpcomponents-client-5.0.x/index.html 

as an optional dependency.

**Comment by marandaneto** [comment]
why would we drop `transport` and `transportGate`?

https://develop.sentry.dev/sdk/unified-api/

> The transport is an internal construct of the client that abstracts away the event sending. Typically the transport runs in a separate thread and gets events to send via a queue. The transport is responsible for sending, retrying and handling rate limits. The transport might also persist unsent events across restarts if needed.

I believe the `connectionFactory` and `transport` should work together and not independently.
Also, `transportGate` must exist unless we move the whole transport implementation for Android from the sentry package to the sentry android core package.

**Comment by maciejwalkowiak** [comment]
Ok, then I need to re-think it. `Transport` returns `TransportResult` - perhaps if we change it to return `Future<TransportResult>`. Currently `Transport` is tightly coupled with the `AsyncConnection`, to introduce NIO we need to change both, but at least at this stage changing `Connection` is not possible. Providing an option to set both connection and transport on `SentryOptions` also does not make sense.

**Comment by marandaneto** [comment]
yeah, merging `AsyncConnection` and `HttpTransport` makes sense, the abstraction came up from the old Java imp, but it's not needed to remain like this, it's just legacy inheritance.

it'd be fine to return a `Future` IMO, it's available since API 1 on Android

**Comment by bruno-garcia** [comment]
The signature of transport in .NET for example is just `Task` (aka: `Future`). No "TrasnportResult" there.

https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/Extensibility/ITransport.cs#L17
