### ISSUE TITLE
Servername no longer defaults to hostname

### ISSUE THREAD

**Issue by francisdb** [getsentry/sentry-java#1109]
_Platform:_
*  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version? openjdk 11.0.8 2020-07-14
*  Logback -> If yes, which version? 1.2.3

_Build system:_
* Other -> If yes, which one? sbt

_Platform installed with:_
* Maven Central

The version of the SDK:
**3.2.0**

---
I have the following issue:

this is a continuation of #992

On sentry 1.x servername was automatically set by picking up the local hostname
On sentry 3.x that default seems to be removed

The legacy docs have this section:

> For many integrations the server name actually corresponds to the device hostname, even in situations where the machine is not actually a server. Most SDKs will attempt to auto-discover this value.

We try to configure sentry without binary dependencies (only properties file/env vars/system properties). Is there a property we can set to have sentry look up the hostname like it used to do?

**Comment by maciejwalkowiak** [comment]
Thanks for reporting. Indeed this is not implemented in 3.x. @bruno-garcia do you think we should add it back?

**Comment by bruno-garcia** [comment]
Thanks for confirming the new behavior @maciejwalkowiak.

When can always report this is `sendDefaultPii` is set to true, in case of the main `sentry` package, because that might be a CLI or desktop app.

In the case of an integration like `spring` we can always set this value since we know as a fact this is the server name, and not a user machine's name.

This is how it was done in .NET vs ASP.NET at least.

Makes sense to add this back, more like a gap given they had it on 1.7. Thanks for testing things out and raising these issues @francisdb, please bare with us while we investigate them and give feedback/address them.
