### ISSUE TITLE
Pass MDC tags as Sentry tags

### ISSUE THREAD

**Issue by maciejwalkowiak** [getsentry/sentry-java#1148]
Users should be able to decide if certain MDC tags are set as Sentry tags so that they can filter by them in the Sentry UI.

This feature was there in 1.7.x.

Related thread: https://forum.sentry.io/t/search-by-mdc-fields/12289

**Comment by yunusual** [comment]
Hello. I'm also looking forward to this change. Searching in Sentry is only possible with tags, therefore, having the ability to create MDC fields automatically as tags will be very useful.

**Comment by dparrella** [comment]
> Hello. I'm also looking forward to this change. Searching in Sentry is only possible with tags, therefore, having the ability to create MDC fields automatically as tags will be very useful.

You can always set `SENTRY_TAGS_TAGNAME` from the environment to create tags. That might not work for all of your MDC data though.

**Comment by adinauer** [comment]
Had a talk with @maciejwalkowiak today:

We'll have to take a look if any other SDKs have a similar feature and if so what config mechanism they use for it.

If we can find any we can replicate the config mechanism from there.

Otherwise we prefer a config property over some convention that just picks up e.g. MDC entries like "sentry.tag.X".
People would have to go over their code and change their MDC keys to match our convention. This might in turn require changes in logging config and other things that act on the logs (and the contained MDC keys).

So our suggestion would be a config setting allowing people to set a list of MDC keys that will be picked up as tags. Our assumption is that people would only have a limited number of MDC keys like sessionId, requestId or similar.

**Comment by marandaneto** [comment]
IIRC Sentry already picks up the tags during SDK init if using one of the configurations, right.https://docs.sentry.io/platforms/java/configuration/#tags

So It'd be fine to have a convention of the sort `sentry.tag.X`, that will be only for the dynamic tags set at runtime.

I agree that if there's another mechanism in place for other SDKs, we should do the same, but I'm unaware of it, @bruno-garcia ?

**Comment by maciejwalkowiak** [comment]
The drawback of having convention like `sentry.tag.X` is that users would have to modify existing applications to comply with this convention. If we would allow a list of tags, for existing applications users could just add Sentry SDK and configure it.

**Comment by marandaneto** [comment]
> The drawback of having convention like `sentry.tag.X` is that users would have to modify existing applications to comply with this convention. If we would allow a list of tags, for existing applications users could just add Sentry SDK and configure it.

Yep, that's a good point, wondering if providing keys only at compilation time would be enough, it'd not work for dynamic key/values.
I'm fine either way, @bruno-garcia might have opinions here since he's handling the customer request.

**Comment by adinauer** [comment]
We could start by implementing the simple version with a list of exact MDC keys.

Then if customers need it we can improve on that by supporting globs and even have a convention by making ["sentry.tag.*"] the default.

**Comment by adinauer** [comment]
Closing now as basic support is here and there's https://github.com/getsentry/develop/issues/539 for potential future improvements.
