### ISSUE TITLE
Read in-app-include and exclude from android manifest metadata

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1176]
I might be missing something but [I can't spot the SDK reading](https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java) from the AndroidManifest.xml the [in-app-include and exclude.](https://docs.sentry.io/platforms/android/configuration/options/#in-app-include)

[Would also be nice to add to the sample](https://github.com/getsentry/sentry-java/blob/main/sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml).

**Comment by marandaneto** [comment]
@bruno-garcia we don't read from the manifest because this is most likely not necessary, we add the App's package automatically to the in-app list.
If one wants to still configure that, they could disable the auto-init mode and set it to the options manually.

also, the manifest does not support list/array values, we'd need to either break by ";" or something else.

**Comment by bruno-garcia** [comment]
Are you aware of a situation where the package name would not be set as `inApp=true`? I noticed some events that were all marked as `inApp=false` and it included system frames and also app frames. Which triggered me to raise this issue.

**Comment by marandaneto** [comment]
@bruno-garcia yes, it could happen, one can create an app with an `io.sentry.mobile.android` package name but having internal libs (which should be inApp=true) and its java packages are named `io.sentry.mobile.jvm`, they don't match because of the last suffix and would mark as `inApp=false`, but as you always say, that would be 1% of the users, as so far we didn't get any complaints.
happy to keep it open, it's indeed an improvement, but we've decided to only support primitive types on the manifest reader, if we decide to support every single option, I'd prefer a single PR for all the missing ones, which is not only in-app-include and exclude.

**Comment by bruno-garcia** [comment]
yeah I understand that edge case, but it doesn't seem to have been the case here. I'll share an example on another channel)
