### ISSUE TITLE
Transactions/Spans finished without status or associated error

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1351]
`SentrySpanAdvice` and `SentryOkHttpInterceptor` do finish a span either with `SpanStatus.OK` or `SpanStatus.INTERNAL_ERROR` (or depending on HTTP response code), also associates the error to the span if any.

`SentrySpanClientHttpRequestInterceptor` does not set an status if `execution.execute` throws nor associates the error.

`SentryTracingFilter` does not associate the error if any.

`SentryTransactionAdvice`  does not set a status if `invocation.proceed` throws nor associates the error.

**Comment by marandaneto** [comment]
@maciejwalkowiak let me know if it was designed like this or just an oversight.

**Comment by maciejwalkowiak** [comment]
`SentrySpanClientHttpRequestInterceptor` - `execution.execute` does not throw when HTTP status != 2xx, but indeed `IOException` could happen so we should handle this.

`SentryTracingFilter` - since exception happens within the scope of transaction it gets associated with the trace in `SentryClient`.

`SentryTransactionAdvice` - you're right, will fix it.

**Comment by marandaneto** [comment]
@Tyrrrz please also double-check that on .NET we do cover those cases, we need to finish the span with status either successfully or not, even associating its error whenever possible.

**Comment by marandaneto** [comment]
Requires #1421

**Comment by marandaneto** [comment]
@maciejwalkowiak can I close this? I guess every change has been tackled right

**Comment by maciejwalkowiak** [comment]
Yep
