### ISSUE TITLE
Provide default fragment breadcrumb implementation

### ISSUE THREAD

**Issue by VladyslavKasprov** [getsentry/sentry-java#1374]
Hi. We use a lot of fragments in our Android application, but we don't get any breadcrumbs for them. Is it possible to add default implementation for collecting fragment breadcrumbs?

P.S. From what I know, we'll have to manually set it in each activity using FragmentManager#registeeFragmenrLifecycleCallbacks.

**Comment by marandaneto** [comment]
@VladyslavKasprov thanks for raising this issue, yes, we're aware of that, the main reason is, there's no global hook that we can access and add our lifecycle callback automatically, you'd need to do it manually for each `FragmentManager`.

2nd reason is that we'd need to depend on `androidx.fragment`, so ideally we'd have a new package so we don't overload our android-core dependency as not everyone uses fragments.

**Comment by VladyslavKasprov** [comment]
Separate dependency and manual hooking would be fine) Thank you) Is there a sample implementation that we can use in the meantime?

**Comment by marandaneto** [comment]
@VladyslavKasprov yes, take a look at the Activity lifecycle for inspiration https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java

if you wish to contribute with a PR, happy to guide :) ideally creating a new Gradle module etc

**Comment by wzieba** [comment]
👋 @marandaneto I'm working currently on a `FragmentLifecycleIntegration` POC but I have a problem with how it should be registered.

My concern is that `SentryAndroid#init` initializes `Sentry SDK` with passed options, [including all default `Integration` objects](https://github.com/getsentry/sentry-java/blob/75a87428fee926621ac397a6ffdeff2499caea8e/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java#L112). It's okay as default `Integration`s rely on `Application` lifecycle so `Sentry SDK` can be initialized when an app is starting.

The challenge I see here is how to add `Integration` during the app runtime. I'd like to add `FragmentLifecycleIntegration` which requires `FragmentManager` later than SDK initialization because when app is starting, I don't have yet access to `FragmentManager`.

My question is: is there any way to add `Integration` after `Sentry SDK` is initialized? If not, can you see a different way to make `FragmentLifecycleIntegration` work?

**Comment by marandaneto** [comment]
@wzieba hey, thanks for your feedback.

`Integrations` and `EventProcessor` can't be added at runtime if not using the passed options.

A way to see this is using the `ActivityLifecycleIntegration` and calling `activity.getFragmentManager()` in the lifecycle methods, but this method is deprecated so likely not fine using it as most of the people already migrated to `androidx.fragment`.

Maybe installing a new `ActivityFragmentLifecycleIntegration` that relies on `androidx.fragment.app` and then  calling `activity.getSupportFragmentManager()`, to add and remove the `FragmentLifecycleIntegration` callback.

this would likely require a new package as the SDK does not depend on the fragments package, like `sentry-android-fragment` module.

you also probably need to set up your SDK in manual mode https://docs.sentry.io/platforms/android/configuration/manual-init. as you need to add your new `ActivityFragmentLifecycleIntegration` integration that also hooks up `FragmentLifecycleIntegration`, this is just an idea though, didn't test it yet.

You'd also need to think about `fragment.getChildFragmentManager()` recursively for every fragment I guess in case you want to execute actions for every child manager.

does that help? let me know if its not clear :) thanks for working on it btw.

**Comment by marandaneto** [comment]
the other option is just to offer the `SentryFragmentLifecycleCallbacks` as people hook up in the `registerFragmentLifecycleCallbacks` themselves, not ideal, yes, but it works.
The OkHttp interceptor is like this https://github.com/getsentry/sentry-java/blob/main/sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt people have to add themselves.

A more risky one is adding bytecode manipulation via Gradle plugin :D

**Comment by VladyslavKasprov** [comment]
> the other option is just to offer the `SentryFragmentLifecycleCallbacks` as people hook up in the `registerFragmentLifecycleCallbacks` themselves, not ideal, yes, but it works.
> The OkHttp interceptor is like this https://github.com/getsentry/sentry-java/blob/main/sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt people have to add themselves.
> 
> A more risky one is adding bytecode manipulation via Gradle plugin :D

Having an option to manually hook up the listener would be good enough. Its fine since most applications these days have very few activities. And even if you have many it's not a big deal.
