### ISSUE TITLE
[JSON] Pluggable JSON parsing to remove GSON dependency

### ISSUE THREAD

**Issue by nwadams** [getsentry/sentry-java#1420]
I am interested in creating a pluggable JSON parsing system to allow for replacing GSON with another parser, such as Moshi that is popular for Android apps to help reduce the app size footprint of the sentry Android library. From my testing `sentry-android` ends up adding ~1.5MB to the app size, but `sentry-android-core` without the NDK bundle only adds about 200-400KB to the download size where a significant percent of that is the GSON library.  

Is there any appetite for a contribution that would refactor to allow a different json parser for Android such as Moshi? This would be a pretty large change, so I want to have a discussion before I begin. 

Some changes (but probably not all) that I see this involving:
- refactoring gson code into its own module. 
- creating a `sentry-android-moshi-extension` module or similar to encapsulate the moshi, or other parsing code. One particular point about moshi is that it is in kotlin so non test code would be in kotlin, in this module. 
- Create a system so the default sentry package was GSON as it is today and an extension package could be added for moshi or other parsers that would exclude gson.

**Comment by marandaneto** [comment]
@nwadams that's definitely something we'd like to collaborate with.

Sounds like a good idea, it could be Kotlin code if Moshi itself is in Kotlin, obviously, the default GSON package should be written in Java.
There are a few GSON adapters in the project, I believe we'd need to work around that.
People could also opt out of GSON if they want to avoid reflection.

Another approach could also be instead of shipping GSON is to copy-paste `JsonWriter` and like, but we'd need to parse the JSONs manually, we've not done that at the beginning for some other reasons, but I don't think we have the same limitation as before.

I like how Retrofit does that with converters https://square.github.io/retrofit/ we could get some inspiration from it.

@bruno-garcia opinions?

**Comment by nwadams** [comment]
Thanks for your comments @marandaneto. I really like the way retrofit does converters. 

I did some more digging into the GSON adapters in GsonSerializer. Most of them don't look too bad and are used to support custom types or enums. 

There is the [UnknownPropertiesTypeAdapterFactory](https://github.com/getsentry/sentry-java/blob/e1a7226bead691b2a824332f3d3a0930e68e33cc/sentry/src/main/java/io/sentry/UnknownPropertiesTypeAdapterFactory.java) which I'm not 100% sure on its purpose so that might be a bit trickier. I suspect this is being used to serialize the Throwable in `SentryBaseEvent`. Is that correct?

It also seems that sentry-java already has a [ISerializer](https://github.com/getsentry/sentry-java/blob/e1a7226bead691b2a824332f3d3a0930e68e33cc/sentry/src/main/java/io/sentry/ISerializer.java) that we might be able to use as the base interface for serialization and deserialization to allow for other implementers.

**Comment by marandaneto** [comment]
> Thanks for your comments @marandaneto. I really like the way retrofit does converters.

no worries, thanks for figuring this out.

> I did some more digging into the GSON adapters in GsonSerializer. Most of them don't look too bad and are used to support custom types or enums.

indeed, those are straightforward.
Also see the usage of `@SerializedName`, only 2 fields because they were Java reserved names.

> There is the [UnknownPropertiesTypeAdapterFactory](https://github.com/getsentry/sentry-java/blob/e1a7226bead691b2a824332f3d3a0930e68e33cc/sentry/src/main/java/io/sentry/UnknownPropertiesTypeAdapterFactory.java) which I'm not 100% sure on its purpose so that might be a bit trickier. I suspect this is being used to serialize the Throwable in `SentryBaseEvent`. Is that correct?

not really, to be honest, I think we could get rid of this but I need to confirm (I'm not even sure that this feature is working as it should).
If you look at our protocol classes, we have this: `private Map<String, @NotNull Object> unknown;`
That means, when serializing/deserializing a JSON object that isn't mapped to a data class, those fields would go to the `unknown` Map so they don't get lost, example:

`{"a": 1, "b": 2}`

`data class(a: Int)`

field/value `b` would be lost because `b` isn't mapped.

the solution with reflection:

`data class(a: Int, unknown: Map<String, Object>)`

so `unknown` contains `"b": 2`

this was a workaround for when adding new fields in the underlying SDKs eg (sentry-native that has NDK support), sentry-android would still forward those new fields before adding the new fields to the protocol, so a release wouldn't be blocked because of that.

a bit complicated, but did you get it? feel free to ask :)

> It also seems that sentry-java already has a [ISerializer](https://github.com/getsentry/sentry-java/blob/e1a7226bead691b2a824332f3d3a0930e68e33cc/sentry/src/main/java/io/sentry/ISerializer.java) that we might be able to use as the base interface for serialization and deserialization to allow for other implementers.

yep, `ISerializer` could be the way to go, but as it's a bigger change, we could do a breaking change if necessary, but still having a pluggable serializer.
See `EnvelopeReader`, this class uses `Gson` but its not using the `ISerializer` interface, we'd need to work on that too, probably reusing `ISerializer` but it has special type adapters.

**Comment by bruno-garcia** [comment]
> Sounds like a good idea, it could be Kotlin code if Moshi itself is in Kotlin, obviously, the default GSON package should be written in Java.

Sounds great!

> Another approach could also be instead of shipping GSON is to copy-paste JsonWriter and like, but we'd need to parse the JSONs manually, we've not done that at the beginning for some other reasons, but I don't think we have the same limitation as before.

This would indeed trim down the size a lot. One downside of it is that we wouldn't be able to pass a whole `Object` to it and let it figure out serialization. We do that on `Extra` and `Contexts` for user-defined types.

> > There is the [UnknownPropertiesTypeAdapterFactory](https://github.com/getsentry/sentry-java/blob/e1a7226bead691b2a824332f3d3a0930e68e33cc/sentry/src/main/java/io/sentry/UnknownPropertiesTypeAdapterFactory.java) which I'm not 100% sure on its purpose so that might be a bit trickier. I suspect this is being used to serialize the Throwable in `SentryBaseEvent`. Is that correct?
> 
> not really, to be honest, I think we could get rid of this but I need to confirm (I'm not even sure that this feature is working as it should).
> If you look at our protocol classes, we have this: `private Map<String, @NotNull Object> unknown;`
> That means, when serializing/deserializing a JSON object that isn't mapped to a data class, those fields would go to the `unknown` Map so they don't get lost, example:
> 
> `{"a": 1, "b": 2}`
> 
> `data class(a: Int)`
> 
> field/value `b` would be lost because `b` isn't mapped.
> 
> the solution with reflection:
> 
> `data class(a: Int, unknown: Map<String, Object>)`
> 
> so `unknown` contains `"b": 2`
> 
> this was a workaround for when adding new fields in the underlying SDKs eg (sentry-native that has NDK support), sentry-android would still forward those new fields before adding the new fields to the protocol, so a release wouldn't be blocked because of that.
> 
> a bit complicated, but did you get it? feel free to ask :)
> 

To elaborate a bit more on this one.

The original idea here was to hold the 'unknown' values somewhere, and when serializing back, they'd go with the same keys they had originally.
The reason for this to exist, is that `sentry-native` which is what our NDK support relies on, can introduce fields that are not known to the Java layer. And in the process of serialize/deserialize would be lost.
Additionally, the SDK could be deserializing an envelope written by another version (i.e: app rolled back the Sentry SDK version) and wouldn't be aware of certain keys.

**Comment by nwadams** [comment]
Got it. Thank you for the context @marandaneto and @bruno-garcia

**Comment by nwadams** [comment]
> > to help reduce the app size footprint of the sentry Android library
> 
> Given this motivation, it would be fair to assume if we drop the dependency to Gson (and read/write json directly without reflection) this issue would no longer be needed?
> 
> I'm asking as we are considering redoing the serialization in order to avoid reflection (to all known protocol types) and a dependency to Gson.

Yeah. That would solve the issue for us completely since no large external libraries would be used that have duplicate functionality

**Comment by marandaneto** [comment]
closed in favor of https://github.com/getsentry/sentry-java/issues/1537
