### ISSUE TITLE
Deprecate `Settings.Secure.ANDROID_ID` in favor of generated InstallationId

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1446]
https://docs.sentry.io/product/security/mobile-privacy/

old Android versions still have a lifetime generated Android_ID https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID

**Comment by bruno-garcia** [comment]
On the migration plan we can add a note and a snippet to users to how to continue with `ANDROID_ID` (i.e: beforeSend set it to User) so that we offer a way to continue with the current user being reported. We do need to warn about the change in user report and how it affects the errors product (but not the release health one).
