### ISSUE TITLE
Support transaction finishing automatically with 'idle timeout'

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1523]
The goal is to have a mode for finishing transactions automatically once no new spans are added to it for N milliseconds, or a general timeout. 

We need to define the spec in the develop.sentry.dev docs and align with other implementations of it. This is an approach used by the JS on the browser (and React Native).

Note On Android: we introduced an opt-out for the auto activity transaction from closing on rendering (it should only add/end span instead of the whole transaction). In that case might not use the idle timeout transaction when that flag is opt-in and rely on the user programatic `finish` call instead.

**Comment by philipphofmann** [comment]
Do we also need this on Cocoa? We currently have there a different approach with waiting for all spans to finish.

**Comment by bruno-garcia** [comment]
@philipphofmann I was just talking about this with @maciejwalkowiak and this other approach came up. Possibly we could have two modes? I'm unsure yet how the 'finish transaction when all spans end' mode will work. For example:

What happens when:
* No span is created from the transaction?
* A span never finishes (i.e: it became a worker thread that doesn't end)

Sounds like we need to discuss this further because likely we can just align on a single approach on all mobile SDKs.

**Comment by AbhiPrasad** [comment]
Figured I'd give some context here for those interested:

JS Browser implementation: https://github.com/getsentry/sentry-javascript/blob/master/packages/tracing/src/idletransaction.ts

An `IdleTransaction` keeps track child spans through the concept of activities. Activities are typed as `Set<span_id>`, where an activity is added when a child span is started, and removed when a child span is finished. When an activity is removed, and the `activities` set becomes empty, the `idleTransaction` finishes itself.

The `IdleTransaction` exposes functionality to register `beforeFinish` callbacks https://github.com/getsentry/sentry-javascript/blob/master/packages/tracing/src/idletransaction.ts#L159, which runs right before the transaction is sent to Sentry. This has to be done because the `IdleTransaction` finishes at an unknown time, so these callbacks have to be set up ahead of time. The browser tracing integration uses this to add measurements and additional spans based on heuristics (like browser specific resource spans). 

In addition, the `IdleTransaction` also trims its end timestamp to match the time of it's last child span end timestamp (as its end timestamp is kind of arbitrary, doesn't have that much value).

Let's talk about some possible gotchas:

1. No child spans are created:

Right now if no child spans are created for an `IdleTransaction`, it will end itself after a configured `IdleTimeout`. This is 1000ms by default, but user-configurable for automatically created pageload/navigation transactions.

 2. Spans never finish

The `IdleTransaction` sets up a heartbeat counter that will ping itself according to a heartbeat timer. If the heartbeat is pinged 3 times, the `IdleTransaction` will finish all of it's active child spans, mark those span's `SpanStatus` as `Cancelled`, and then finish itself.

3. The polling problem aka: 1 -> 0 -> 1 -> 0 

To prevent "polling" child spans from increasing transaction duration, after the `IdleTransaction` hits 0 activities for the first time, we call `transaction.finish()` after a set timeout. This is to prevent a transaction from going on infinitely if a user keeps adding child spans. As a consequence of this though, there might still be unfinished spans on a transaction, even if the transaction is finished. 

Here's an example situation: idle transaction is created -> idle transaction starts child spans (activities) -> idle transaction activities hit 0 (all active spans have finished) -> transaction sets timeout to call `.finish()` -> child spans get added to transaction -> transaction calls `.finish()` -> latter child spans do not get recorded because they have not called `.finish()`.

**Comment by marandaneto** [comment]
with the `waitForChildren` feat, `io.sentry.traces.activity.auto-finish.enable` will likely get deprecated, I don't see a reason why having it anymore.

**Comment by marandaneto** [comment]
Draft PR for fragment performance https://github.com/getsentry/sentry-java/pull/1528 using the `waitForChildren` feat

**Comment by rhcarvalho** [comment]
We may also consider how this special transaction will behave as we focus more on spans, and one day be able to ingest data without buffering full transactions in memory.

Perhaps, if we make the functionality of "automatically finish" available to any span, that would put us in a better future position, not tied to transactions.
