### ISSUE TITLE
does the `contexts.trace`  have a `data` field?

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1540]
RN transaction contains:

```
"trace": {
      "data": {
        "route": {
          "name": "Tracker",
          "key": "Tracker-hG_pz0b0lCt-nw6L5N2-J",
          "params": {},
          "hasBeenSeen": false
        },
        "previousRoute": {
          "name": "Home",
          "key": "Home-jyGN9hsqW_uBVE50Tjp2T",
          "params": {}
        }
      },
      "op": "navigation",
      "span_id": "ae1192f4fbda20ff",
      "tags": {
        "routing.instrumentation": "react-navigation-v5",
        "routing.route.name": "Tracker"
      },
      "trace_id": "1e5acd8e53254c9db2be50cb40e9ada4"
    }
```

this section does not say much https://develop.sentry.dev/sdk/event-payloads/transaction/#contextstrace so I am not sure rather we should have it or not

**Comment by marandaneto** [comment]
@rhcarvalho do you know the answer by any chance?

**Comment by jennmueng** [comment]
`contexts.trace` is serialized here on the JS SDK:
https://github.com/getsentry/sentry-javascript/blob/9af1886e7ee6ca7be3f12050b044c73725783575/packages/tracing/src/transaction.ts#L119-L130

`getTraceContext()` is the same as a span's, so `context.trace.data` is the same as `span.data`

**Comment by marandaneto** [comment]
Similar to https://github.com/getsentry/sentry-java/issues/1233

it does not look like `context.trace.data` should be there, there's no public API to add data to the tracer but rather to the span only.
so if you have multiple spans, which span.data goes into the trace.data?

**Comment by marandaneto** [comment]
cc @maciejwalkowiak @bruno-garcia opinions?

**Comment by jennmueng** [comment]
> so if you have multiple spans, which span.data goes into the trace.data?

It would just be the transaction's own data right, as `Transaction extends Span`?

**Comment by marandaneto** [comment]
the `Trace` object that goes under the `Contexts` is not a `Transaction` nor a `Span` afaik.

**Comment by jennmueng** [comment]
@marandaneto AFAIK on JS that's actually the case, that the `context.trace` comes from a `Span`: https://github.com/getsentry/sentry-javascript/blob/a6f8dc26a4c7ae2146ae64995a2018c8578896a6/packages/types/src/span.ts#L162-L171

**Comment by bruno-garcia** [comment]
I'd defer to @rhcarvalho to clarify which way we should go here. /cc @maciejwalkowiak @Tyrrrz

**Comment by Tyrrrz** [comment]
We don't have `data` on `contexts.trace`:
https://github.com/getsentry/sentry-dotnet/blob/f20b3f072f08fb451e08a9f7ae97329d0d18bdb2/src/Sentry/Protocol/Trace.cs#L51-L64

**Comment by rhcarvalho** [comment]
> does the contexts.trace have a data field?

No. It has:

```
TraceID
SpanID
ParentSpanID
Op
Description
Status
```

This question was already discussed in https://github.com/getsentry/develop/issues/244#issuecomment-778694182.

The current implementations are still inconsistent in this regard. I'd recommend using `Event.Extra` for now and updating the spec about the conversion from Transaction to Event, since `Event.Extra` already exists with the same type as `Transaction.Data`. And then we can probably close the issue above from the `develop` repo.

For reference, that's what we did for Go https://github.com/getsentry/sentry-go/pull/329.

I see the problem where JS and Java fall out of alignment impacting React Native -- I see no problem with changing the JS implementation to match.

BTW, an argument in favor of having smaller "TraceContext" is that it gets attached to outgoing error events. All we need in that case are the IDs (trace id and span id) to match errors and transactions, all the rest is just excess payload.

**Comment by marandaneto** [comment]
@rhcarvalho thanks for the detailed answer, would you mind then raising an issue to the JS repo and linking to this one? so we can close this one, as `contexts.trace` should not have the `data` field anyway, but its coming from JS/RN and being lost during round trip ser/deser on Android
