### ISSUE TITLE
Add support for tracing origins

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-java#1585]
Currently the [SentryOkHttpInterceptor](https://github.com/getsentry/sentry-java/blob/aca78d9ca024c75225e59c36e35622055d2f6cbf/sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt#L33-L35) adds the [sentry-trace HTTP header](https://develop.sentry.dev/sdk/performance/#header-sentry-trace) to every HTTP request. Some HTTP requests are targeting backends that don't have support for the sentry-trace HTTP header. Therefore JavaScript has the concept of [tracingOrigins](https://docs.sentry.io/platforms/javascript/performance/instrumentation/automatic-instrumentation/#tracingorigins), which is a list of URLs to which the integration should append the sentry-trace HTTP header.

**Comment by philipphofmann** [comment]
Related to https://github.com/getsentry/sentry-cocoa/issues/1199.

**Comment by bruno-garcia** [comment]
It makes sense that the trace id doesn't need to go to all endpoints an App talks to. Currently it can be filtered with the callback the integration offers but we could look at adding the same options as the browser JS SDK.
Worth noting the browser adds that because of CORS:

> You will need to configure your web server CORS to allow the sentry-trace header. The configuration might look like "Access-Control-Allow-Headers: sentry-trace", but the configuration depends on your set up. If you do not allow the sentry-trace header, the request might be blocked.

So we have less of a need here since CORS doesn't apply here.
