### ISSUE TITLE
Using custom sentry-native library with Android SDK

### ISSUE THREAD

**Issue by triplef** [getsentry/sentry-java#1626]
Our Android app uses both Java and native C/C++ code with Qt, and we’d like to take advantage of the optional Qt integration in sentry-native, which is not enabled for the sentry-native library bundled with the Sentry Android SDK from Maven Central.

Is it possible to use a self-compiled sentry-native library in combination with the sentry-android SDK?

**Comment by bruno-garcia** [comment]
@triplef I might be wrong here and @Swatinem can call em out but assuming all there is to it is compiling with the Qt flags, it's probably fine to just replace the `libsentry.so` in the `sentry-android-ndk.aab` with your own version since we don't do anything fancy when compiling [`sentry-native`](https://github.com/getsentry/sentry-native):

https://github.com/getsentry/sentry-java/blob/82dbee6c32c99a419e2c9874e814033c8a596a2e/sentry-android-ndk/CMakeLists.txt#L1-L17

You could possibly fork this repo, change the `CmakeLists` we use and build from source. If you choose this route, I suggest sticking to a tagged version of the SDK (i.e: [checkout tag 5.0.1](https://github.com/getsentry/sentry-java/releases/tag/5.0.1) to stay on a proper 'release')

**Comment by triplef** [comment]
Thank you for the quick input on this @bruno-garcia!

This sounds like it should work fine, but I'd like to see if there's a way we can keep using the official builds of the Android SDK to keep things simple. 

I'm not entirely clear on how linking works with AABs, but would it work to keep using the Android SDK from Maven Central and just link our Qt project against a self-built sentry-native.so with Qt support? We already extracted the native library from the AAB in order to call functions from sentry-native from our native code, so it would be easy to just replace that with a custom build, but I'm unsure which library the linker would end up using.

**Comment by marandaneto** [comment]
@triplef that makes sense.

> SENTRY_INTEGRATION_QT (Default: OFF): Builds the Qt integration, which turns Qt log messages into breadcrumbs.

@Swatinem would be possible to turn this on by default for Android builds? is there any side effect rather than package size ?

**Comment by triplef** [comment]
> > SENTRY_INTEGRATION_QT (Default: OFF): Builds the Qt integration, which turns Qt log messages into breadcrumbs.
> 
> @Swatinem would be possible to turn this on by default for Android builds? is there any side effect rather than package size ?

I believe this will require linking against Qt libraries, so that wouldn’t work for the default case, unless there was a way to resolve these symbols at runtime if available. It would definitely be nice if the Android SDK were to support Qt out of the box.

**Comment by marandaneto** [comment]
last case a pre-compiled package would work too, like `sentry-android-qt` which does the linking against the Qt libraries, but the package would be added manually along with `sentry-android` instead of a transitive dependency of `sentry-android`

**Comment by Swatinem** [comment]
As @triplef mentioned, building for Qt by default would mean that the Qt libraries are required at runtime so that is not the way to go.

If you want to continue using the pre-build/packaged version of sentry-native, you can do so, and just vendor/copy-paste the integration into your own code. It is super tiny, and does not depend on any sentry-native internals. All the integration does right now is capture Qt logs as sentry breadcrumbs.

https://github.com/getsentry/sentry-native/blob/master/src/integrations/sentry_integration_qt.cpp

**Comment by triplef** [comment]
Ah nice, that seems like the most straightforward solution. Thank you @Swatinem!
