### ISSUE TITLE
sentry-spring not reporting errors from spring services 

### ISSUE THREAD

**Issue by bhavayAnand9** [getsentry/sentry-java#1636]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [x]  Spring -> If yes, which version? 5.1.20

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [x]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [x]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
**5.0.1**

---
I have the following issue:
Sentry is not reporting errors that are explicitly thrown inside the spring service.

The description goes here ...
I'm trying to integrate sentry using sentry-spring v5.0.1, but errors are not getting reported in the dashboard.

my SentryConfig class
```
@configuration
@Import({ApplicationConfig.class})
@EnableSentry()
public class SentryConfig {

@PostConstruct
initSentry() {
  Sentry.init(...set dns & tags);
}

}
```

if I call `captureException` from some Service, this error won't make it to the sentry dashboard.
```
Sentry.captureException(new Error("sentry is working on local..."));
```
but If I put this same line in the SentryConfig file after `Sentry.init`, it gets reported.

Am I doing this wrong or is it expected?
Do I have to call `Sentry.init` inside every other class?

Not sure if this helps,
I tried debugging this, the program goes into a NoOpHub file & an EMPTY_ID gets returned from there & no call was made to the sentry server.

I've gone through issues on GitHub, sentry forum & SO results but had no luck with this issue.

Thanks

**Comment by maciejwalkowiak** [comment]
@bhavayAnand9 there are at least 3 ways you can go to integrate Sentry into Java app:

1. for Spring Boot applications - use `sentry-spring-boot-starter` ([docs](https://docs.sentry.io/platforms/java/guides/spring-boot/))
2. for plain Spring (no Spring Boot) - use `sentry-spring` - this is where `@EnableSentry` comes from ([docs](https://docs.sentry.io/platforms/java/guides/spring/)) - you don't call `Sentry.init` there manually, as Spring integration inits Sentry for you
3. initialise and configure Sentry manually with `Sentry.init(...)`

You'll find a sample app for each of the above in the [sentry-samples](https://github.com/getsentry/sentry-java/tree/main/sentry-samples) directory.

In all cases, when you don't see your events in the dashboard its useful to turn on SDK `debug` mode. 

1. for Spring Boot it would be settting `sentry.debug=true` in `application.properties`.
2. for Spring `debug=true` in `src/main/sentry.properties`
3. for plain Java:

```
Sentry.init(options -> {
    ...
    options.setDebug(true);
});
```

I hope it will help you to figure out what the issue is. If not, please paste the SDK debug output here and ideally attach a sample project, either as a zip file or a separate github repository that reproduce an issue.

**Comment by bhavayAnand9** [comment]
Thanks @maciejwalkowiak , that resolved my issue

but using `@EnableSentry` has one more issue, it requires a constant string. Is there any other way to configure DSN during runtime?

**Comment by maciejwalkowiak** [comment]
Created issue for this https://github.com/getsentry/sentry-java/issues/1640
