### ISSUE TITLE
When Android capture unhandled exception, let the app do not crash immediately, but instead give sentry several seconds to upload exceptions to server

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-java#1643]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [x]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Proguard/R8:_
- [x]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
sentry-flutter  5.0.0

---
I have the following issue:

We know that (https://github.com/getsentry/sentry-dart/issues/548), if a crash happens, the user have to **start the app again** in order to let sentry upload the event to server. However, consider the following two cases: 

1. What if the app crash continuously when starting? In this case, sentry never have a chance to upload! This is almost the MOST severe bug an app can have, if it happens. But it even DOES NOT show up in sentry webpage!
2. What if the user does not start the app again? For example, an impatient user. More importantly, a reviewer of the Android app store - often he just test once, see it crash, then reject this app *without starting the app again*. In this case, the app can never know the bug that the reviewer sees.

Proposal: show a dialog to user saying "bug occurred, please wait for several seconds", while sentry upload event to server in the backend. Instead of simply crashing and quit immediately.

**Steps to reproduce:**
- see above

**Actual result:**
- see above

**Expected result:**
- see above

**Comment by fzyzcjy** [comment]
@marandaneto My suggestion is on the *shutdown* procedure, not the *startup* of next run. See the reasons above for why I suggest this ;)

**Comment by marandaneto** [comment]
@fzyzcjy yep I know, but the NDK integration doesn't have a transport that sends an event to Sentry, it only writes a file to the disk which is picked up on restart and sent it over to Sentry via the Java transport, otherwise we have to change quite a lot of things, but we'll take into consideration, whats the best approach and improve from there, thanks.

**Comment by fzyzcjy** [comment]
@marandaneto We may treat the two differently. For android errors, it can be uploaded before shutdown; for ndk, need to upload the next time.

You are welcome!

**Comment by fzyzcjy** [comment]
@marandaneto The reason is that, it is much rare for android people to see ndk bugs compared with java bugs, so by adding this proposed feature, a major part (instead of minor part) can be benefited ;)

**Comment by romtsn** [comment]
We tackled this as part of #2277 - it does not cover all the cases, but just the first point in the original issue. Instead of blocking the main thread after a crash occurs, we are blocking it on the next app start if we encountered a startup crash in the previous run, allowing the app to upload events to Sentry. This will mitigate the recurrent startup crashes issue.

As for the problem when the user never launches the app again, we'll tackle this as part of #598 if ever implemented. Hence, closing the issue
