### ISSUE TITLE
Scope clones the transaction but it should not

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1701]
bug introduced in #1496

we have to confirm this behaviour but I am pretty sure it should not

**Comment by marandaneto** [comment]
@bruno-garcia can you confirm?

**Comment by bruno-garcia** [comment]
Looks like it's not cloning. It copies the reference thouhg:
```
    this.transaction = scope.transaction;
```

https://github.com/getsentry/sentry-java/pull/1496/files#diff-9cb115b44ee4c6940b189c33ba24e7b6a168271eefc02f6c0d6c053e75da94c5R83

I believe that's the right thing so that in a server if you push a scope, you can still find the transaction and create children.

**Comment by marandaneto** [comment]
copying the reference is also done by the .NET/Python SDK, so I'll close it.
https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/scope.py#L473
