### ISSUE TITLE
sentry-spring-boot-starter

### ISSUE THREAD

**Issue by o0hailang0o** [getsentry/sentry-java#1868]
The Java environment sentry spring boot starter is not easy to install sentry 9.1.2. sentry1. 7.23 official methods are easy to use.

**Comment by bruno-garcia** [comment]
@o0hailang0o Sentry SDK for Java (including the spring boot integration) are not supported by Sentry 9. That's because it relies on Envelopes which was a format/endpoint added back in 2019 or so. We mention that breaking change in the migration docs and release pages.

We strongly recommend you upgrade your Sentry (which include a ton of features like Release Health, Performance Monitoring, Discover, Dashboards and more).

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/self-hosted
