### ISSUE TITLE
Add a way to control built-in event builders via option

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#222]
The most common reason people need to write their own `RavenFactory` is to do small adjustments to which event builders get called.

We should probably,
- Publish a list of default event builders used
- Allow some way to enable additional event builders via option
- Allow some way to disable default event builders via option

**Comment by tkaemming** [comment]
A few offhand thoughts:

- The iterable of builders should probably be a set rather than a list — helpers shouldn't have implicit data dependencies where they require other helpers to have previously set state on the builder to execute successfully.
- It'd be great if we could find a way to solve the [X-Forwarded-For example from the README](https://github.com/getsentry/raven-java#custom-ravenfactory) with this pattern as well.

**Comment by marandaneto** [comment]
Sentry-Java SDK v3 do not use builders anymore
