### ISSUE TITLE
SDK for Quarkus

### ISSUE THREAD

**Issue by henka-rl** [getsentry/sentry-java#2254]
### Problem Statement

I would like Sentry to implement an SDK for Quarkus in the same way as for Spring Boot

**Comment by LaurentTreguier** [comment]
> Yes, I know about https://github.com/quarkiverse/quarkus-logging-sentry. But I believe that implementation just initialize Sentry. I can't see that is an automatic instrumentation for http as in your Spring Boot SDK.

@henka-rl 
I don't know if this is still relevant to you 9 months after your original comment, but I just tried setting up `quarkus-logging-sentry` (version 2.0.1 as of writing this) and successfully got an error logged in Sentry by throwing an exception inside an HTTP endpoint

**Comment by LaurentTreguier** [comment]
Ah, I see; that makes more sense indeed

**Comment by LaurentTreguier** [comment]
After a some research and quite a bit of head-scratching, I managed to get something using OpenTelemetry. Here are the general steps:
- I made a Sentry extension very much like `quarkus-logging-sentry`, as a subproject of my main project
- I added the following dependencies to said extension subproject:
  - `io.quarkus:quarkus-opentelemetry` (deployment and runtime)
  - `io.sentry:sentry-opentelemetry-core` (deployment and runtime)
  - `io.sentry:sentry-jul` (runtime only)
  - `io.opentelemetry.instrumentation:opentelemetry-jdbc` (runtime only)
- Having the `Sentry.init` in my project means I could set it up for OpenTelemetry, as per Sentry's documentation
- I made a bean producing a `SentrySpanProcessor` singleton, and added it to the extension's deployment processor since it is needed at runtime (it will get picked up by `quarkus-opentelemetry`)
- I implemented a custom `ConfigurablePropagatorProvider` that provides a `SentryPropagator` with the `"sentry"` name
- I added a `META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ConfigurablePropagatorProvider` file with the fully qualified name of said propagator
- Finally, I added `quarkus.otel.propagators=tracecontext,baggage,sentry` inside `application.properties`, making OpenTelemetry use the Sentry propagator

This should be all that's needed; although I'm guessing the new classes should also added as reflective classes in order to work in native builds (which I haven't tested).

All in all, it involves a bit of manual work; but I got call transactions in Sentry (correctly linked to issues when needed), as well as some JDBC stuff. If I go forward with this, I'll link it in this comment for anyone stumbling upon this issue in the future

**Comment by adinauer** [comment]
Thanks for sharing @LaurentTreguier. I guess the provider for `SentryPropagator` is something we could add to the SDK package itself. I've added it to https://github.com/getsentry/sentry-java/issues/2419

**Comment by colin-mckenzie-addepar** [comment]
Hello.

(Apologies in advance if this question should belong in it's own thread - I can create if needs be - but is related to this one.)

In the absence of a Quarkus SDK, what is the recommended way to manually instrument code for performance and error data given the reactive nature of a Quarkus app - see: https://quarkus.io/version/main/guides/mutiny-primer

Specifically for the setting of tags that only relate to the current request (like a `user_id` pulled from jwt token passed with the an API request).
Reading the docs it wasn't clear to me how scopes should be used in the context of a Quarkus app.

In the example below I am using the SLF4J mapped diagnostic context (MDC) to store a `user_id` at the start of an API request then using `beforeSend` and `beforeSendTransaction` to set it on the event.

Is this a safe and acceptable pattern? Are there other recommendations?

Thanks - Colin

```
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;
import io.quarkus.runtime.StartupEvent;

@ApplicationScoped
public class SentryConfig {

  void onStart(@Observes StartupEvent ev) {
    Sentry.init(
      options -> {
          options.setDsn("https://my.dsn");
          options.setTracesSampleRate(1.0);
          options.setEnvironment("development");
          options.setTag("global_tag", "always-the-same");
          options.setBeforeSend((event, hint) -> {
              event.setTag("user_id", MDC.get("user_id"));
              return event;
          });
          options.setBeforeSendTransaction((event, hint) -> {
              event.setTag("user_id", MDC.get("user_id"));
              return event;
          });
      });

```

**Comment by adinauer** [comment]
@colin-mckenzie-addepar I'm not familiar with Quarkus but this should work in theory. Maybe another Quarkus user can help you out here in case you run into problems.
