### ISSUE TITLE
Align span `op` spec

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#2261]
### Description

https://github.com/getsentry/develop/issues/693

<img width="1072" alt="Screenshot 2022-09-28 at 09 16 14" src="https://user-images.githubusercontent.com/5731772/192713352-924d61ce-ede8-4a66-96a5-49ed657b0e66.png">

| SDK             | Old Operation                             | New Operation                                  | Link                                                                                                                                                                  | PR                                                         |
| --------------- | ----------------------------------------- | ---------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| Java            |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | < graphql op name >                       | http.graphql.< op-name >                       | https://github.com/getsentry/sentry-java/blob/e2ea31c73c93aa587941cb7ea9254f853786db26/sentry-apollo/src/main/java/io/sentry/apollo/SentryApolloInterceptor.kt#L88    |                                                            |
|                 | < objectType >.< segment >                | ???                                            | https://github.com/getsentry/sentry-java/blob/e2ea31c73c93aa587941cb7ea9254f853786db26/sentry-graphql/src/main/java/io/sentry/graphql/SentryInstrumentation.java#L136 |                                                            |

**Comment by AbhiPrasad** [comment]
So this is still undecided on what these should change to, so feedback here is welcome. We can always also amend the develop docs based on this.

**Comment by marandaneto** [comment]
> So this is still undecided on what these should change to, so feedback here is welcome. We can always also amend the develop docs based on this.

Yep, @romtsn said he's gonna take a look at it.

**Comment by romtsn** [comment]
@AbhiPrasad so here's the summary:

### [SentrySpanAdvice](https://github.com/getsentry/sentry-java/blob/main/sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanAdvice.java#L70)

Pretty straightforward, because we can treat this essentially as a manual instrumentation/span. Users have to manually add a `@SentrySpan` annotation to the methods they want to create spans for, they can also (optionally) provide a value which will be used as a span `op`. If they don't, then the instrumentation defaults to the owner className + methodName.

I don't think we need to have a strict span op for that, since again, it's manual instrumentation.

### [SentryInstrumentation](https://github.com/getsentry/sentry-java/blob/c92eb47ff779b7ab83147a3694f2e51680b9e641/sentry-graphql/src/main/java/io/sentry/graphql/SentryInstrumentation.java#L136) 

The first part will be set to the type that contains the queried fields. For root operations it'd be one of `[query|mutation|subscription]`, otherwise it'd be the parent type; the second part is set to the field being queried.

For example, for this query:
```
query ShowsAndActors {
    shows {
      actors {
        name
      }
    }
}
``` 
There will be 2 spans: `query.shows` and `show.actors`.

I think what you suggested should work here, so either just `graphql` or maybe `graphql.server` as op name, and description would contain the type + queried fields then.

### [SentryApolloInterceptor](https://github.com/getsentry/sentry-java/blob/f3f2ab88b17fb9d9460ed28e259716e628019913/sentry-apollo/src/main/java/io/sentry/apollo/SentryApolloInterceptor.kt#L89)/[SentryApollo3Interceptor](https://github.com/getsentry/sentry-java/blob/f3f2ab88b17fb9d9460ed28e259716e628019913/sentry-apollo-3/src/main/java/io/sentry/apollo3/SentryApollo3HttpInterceptor.kt#L86)    

It will either set the op to the operation name or `apollo.client`, e.g. this query:
```
query LaunchDetails($id:ID!) {
  launch(id: $id) {
    id
    site
    mission {
      name
      missionPatch(size:LARGE)
    }
  }
}
```
will set it to `LaunchDetails`.

`http.graphql.[query|mutation|subscription]` should be fine here I guess. Or it could also be `graphql.client.[query|mutation|subscription]`. The description already contains the operation type + name anyway.

cc @adinauer

**Comment by marandaneto** [comment]
@romtsn 

> I don't think we need to have a strict span op for that, since again, it's manual instrumentation.

If we want to leverage our performance issues feature for AOP instrumentation, we'd need a defined `op`, the details can go under the description.

Do you have any suggestions here?

**Comment by romtsn** [comment]
> @romtsn
> 
> > I don't think we need to have a strict span op for that, since again, it's manual instrumentation.
> 
> If we want to leverage our performance issues feature for AOP instrumentation, we'd need a defined `op`, the details can go under the description.
> 
> Do you have any suggestions here?

I was not aware we can detect slow **custom** spans. Could you provide more details on how we would do that? Will we allow users to set their custom thresholds for slow spans?

**Comment by marandaneto** [comment]
@romtsn This is [new](https://docs.sentry.io/product/issues/) and I don't have more context about that, but this feature requires a pre-defined `op` and that's all we need for now afaik.

**Comment by romtsn** [comment]
Sorry, I don't understand how can we have a pre-defined `op` for custom spans, therefore I don't have any suggestions for this specific case.

**Comment by AbhiPrasad** [comment]
> Users have to manually add a @SentrySpan annotation to the methods they want to create spans

If these are methods, could we default to applying the `function` operation name? They are using the annotation the measure the time of a function call right? Users can overwrite this if they want. This is in-line with some of the other usages of `function` that we have in other SDKs.

> then the instrumentation defaults to the owner className + methodName

Can this be the span description instead? The operation than will stay consistent, while the description can have a higher range of unique values.

**Comment by romtsn** [comment]
> If these are methods, could we default to applying the `function` operation name? They are using the annotation the measure the time of a function call right? Users can overwrite this if they want. This is in-line with some of the other usages of `function` that we have in other SDKs.

sounds good 👍 

> Can this be the span description instead? The operation than will stay consistent, while the description can have a higher range of unique values.

Yes, we can default to this for the description. It can be still overwritten by users though, but I think it's alright.

As for the other 2, can we agree on `http.graphql.[query|mutation|subscription]` for clients and `graphql` for servers?

**Comment by AbhiPrasad** [comment]
> As for the other 2, can we agree on http.graphql.[query|mutation|subscription] for clients and graphql for servers?

Sounds good to me!
