### ISSUE TITLE
Enable enableAutoFragmentLifecycleTracing via Sentry Android Gradle Plugin.

### ISSUE THREAD

**Issue by prashanOS** [getsentry/sentry-java#2318]
### Problem Statement

I'd like to avoid having to install the Fragment library manually (https://docs.sentry.io/platforms/android/configuration/integrations/fragment/#configure) - but it seems that the Sentry Android Gradle Plugin does not expose a way to configure `enableAutoFragmentLifecycleTracing`. 

Our app is a single activity app that uses one fragment per screen, so the default transactions and profiling for activity are not very useful to us.

### Solution Brainstorm

Seems like we could add another value to the `InstrumentationFeature` enum (and potentially automatically enable this if the Fragment library is included?)

**Comment by romtsn** [comment]
Sorry, I didn't get what exactly you'd want to achieve - do you want to *disable* or *enable* autoFragmentLifecycleTracing? Because it's actually enabled by default, when it gets auto-installed through the plugin, see here: https://github.com/getsentry/sentry-java/blob/649f1714ddbef043ded98bd491c19293d0a254f3/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java#L206-L208

**Comment by prashanOS** [comment]
> Sorry, I didn't get what exactly you'd want to achieve - do you want to _disable_ or _enable_ autoFragmentLifecycleTracing? Because it's actually enabled by default, when it gets auto-installed through the plugin, see here:
> 
> https://github.com/getsentry/sentry-java/blob/649f1714ddbef043ded98bd491c19293d0a254f3/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java#L206-L208

Hmmm... I want to _enable_. But this 1) doesn't match your documentation, and 2) doesn't seem to be working as I'm not seeing any Fragment transactions/profiles in Sentry.

**Comment by romtsn** [comment]
1) Yeah, but you are referring to the docs from the *manual* installation, if you take a look at the previous [section](https://docs.sentry.io/platforms/android/configuration/integrations/fragment/#auto-installation-with-the-sentry-android-gradle-plugin), we state that both flags will be enabled, but you still can override them if needed:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/4999776/197864057-391e2873-9f7f-4e8b-a559-bbcbb64b2c26.png">

2) This is because the Fragment integration does not create transactions, but spans. If there's no ongoing transactions, the spans won't be created. We have an issue for that, but it hasn't been implemented yet. https://github.com/getsentry/sentry-java/issues/1810

**Comment by prashanOS** [comment]
Ah got it, thanks! I see that issue is quite old - is this on the roadmap for the near future? If not, is there documentation that shows how we might do this ourselves in our app code?

**Comment by romtsn** [comment]
Yes, we'll try to get to it this in the next 3 months. There's no docs specifically for this kind of transactions, but you can refer to how we do it for Activities and try to replicate it for fragments https://github.com/getsentry/sentry-java/blob/f809aac909438b44db626a73c440d386c2321f63/sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java#L152-L211

Alternatively, you can try to [disable](https://docs.sentry.io/platforms/android/performance/instrumentation/automatic-instrumentation/#androids-activity-instrumentation) `auto-finish` of the activity transactions, so all fragment spans will be captured as long as the activity transaction is alive. There still will be a single Activity transaction, but at least it will capture all fragment lifecycle ops as spans.
