### ISSUE TITLE
NPE in ProfileInstallReceiver because Sentry SDK using outdated androidx.profileinstaller version

### ISSUE THREAD

**Issue by paulinar** [getsentry/sentry-java#2384]
### Problem Statement

After I integrated my app with the Sentry Android SDK, some of our users started hitting the "NPE in ProfileInstallReceiver" bug that Google fixed recently. The fix was deployed in `androidx.profileinstaller:profileinstaller:1.3.0-alpha01` but the Sentry SDK uses `androidx.profileinstaller:profileinstaller:1.2.0`. Will your team be updating your dependency version soon to get this fix?

See this link for more details: https://issuetracker.google.com/issues/243851384?pli=1

**Comment by romtsn** [comment]
I'm afraid we cannot use non-stable versions, so we'd have to wait until `1.3.0` becomes stable.
Also, this seems like a transitive dependency, do you know where it's coming from?

**Comment by paulinar** [comment]
Understood! 

Yes it is a transitive dependency, coming from the Sentry Android SDK

**Comment by romtsn** [comment]
yeah, but we don't use it directly https://github.com/getsentry/sentry-java/blob/3695453b26c0145ad6fd6802f73e742847807048/sentry-android-core/build.gradle.kts#L86-L88

That's why I asked if you know where it _really_ is coming from :)  Are you using compose in your app? It looks like compose itself has not updated the version yet https://github.com/androidx/androidx/blob/androidx-main/compose/ui/ui/build.gradle#L82

**Comment by paulinar** [comment]
Ah yes you're right, it's coming from the Compose dependency, my apologies and thank you for clarifying!
