### ISSUE TITLE
sentry-spring-boot-starter not working for Spring 3

### ISSUE THREAD

**Issue by santos-samuel** [getsentry/sentry-java#2442]
### Integration

sentry-spring-boot-starter

### Java Version

17

### Version

6.10.0

### Steps to Reproduce

1. Create Spring Boot Project with Java 17 and Sentry.
2. Follow Sentry configuration steps for spring boot (https://docs.sentry.io/platforms/java/guides/spring-boot/)

### Expected Result

Sentry.captureException() sends event to Sentry dashboard.

### Actual Result

Events were not reaching Sentry's server.
Only when I manually configured Sentry (like shown below) the event reached Sentry's server.
```
@Configuration
class SentryConfiguration {
	public SentryConfiguration(@Value("${sentry.dsn}") String sentryDsn) {
		Sentry.init(sentryDsn);
	}
}
```

I debugged a little a saw that Sentry's internal hub instance (from the `Sentry` class), was not being initialized.
The properties from the application.properties were not being set at all.

**Comment by lbloder** [comment]
Hello @santos-samuel,
We have a separate integration for Spring Boot 3 and Spring 6 due to the move from javax to jakarta.
The `spring-boot-starter` Integration uses the javax package can be used for Spring Boot < 3. Could you give `spring-boot-starter-jakarta` a try and report back if that works as expected?

Sorry for the confusion, Iooks like the docs aren't updated yet.

**Comment by santos-samuel** [comment]
Yeah, that was issue.
Thanks!
