### ISSUE TITLE
Add enableTracing option

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-java#2522]
A new simplified options for configuring to turn tracing & performance on should be added to all SDKs. For each SDK the default sample rate should be agreed upon.  

Docs do not need to be updated yet, nor the onboarding wizard. This can wait until the top level options are added to a number of SDKs and we decide if we want to configure the default onboarding experience, for all new users.

See [develop docs](https://develop.sentry.dev/sdk/performance/#enabletracing) for more information. This is a non-breaking change to be clear. Any of the three options should enable performance, alone or in combination

### Open point:
recommend default it 1.0 or 100%. Can discuss if it should be less.

**Comment by smeubank** [comment]
@romtsn @adinauer @kahest ideally this will be added on Android and Java, could understand if the default sample rate might need to be different for FE vs server-side applications

**Comment by romtsn** [comment]
@smeubank so, what's the expected behavior here? From the docs it seems like either of the options can enable performance monitoring, but from the go-sdk release notes it seems like, it should be both `enableTracing` AND the sample rate? It's still unclear.

![image](https://user-images.githubusercontent.com/4999776/217571254-5bf160b8-97da-47a8-8be9-7ab691cdc4a0.png)
