### ISSUE TITLE
[Kotlin] Wrong line number from captureMessage

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-java#2763]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.5

### Proguard

Disabled

### Version

6.19.0

### Steps to Reproduce

1. Create a new Kotlin app
2. Send an event using `Sentry.captureMessage` from a inline function:

```
inline fun Any.sendMessage(message: () -> String) {
        Sentry.captureMessage(message())
    }
...
sendMessage {"Sentry captureMessage test using inline fun extension line 32"}
``` 

Most likely caused by compiler options that changes the inline function to the end of original file. 

### Expected Result

The trace points to the lines where the function are called.

### Actual Result

The reported line is a new line at the end of the file, in my example my file has 65 lines and the reported line is 66.

**Comment by stefanosiano** [comment]
I'm going to investigate on the techniques we use to get the line number. Aligning it with the `Sentry.captureException` one should improve it.
I'll build a sample and post an update

**Comment by markushi** [comment]
We need to further investigate into this, looks there are Android API changes which could be relevant for this.

**Comment by stefanosiano** [comment]
Here's the findings:
Let's say in a class there is 

```
fun a() {
    ...
    b()
    ...
}

inline fun b() {
    ...some code...
}
```
If an Exception occurs in `a()` everything is fine
If an Exception occurs in `b()` line number is wrong
Same happens with `Thread.getStacktrace()`:
Thread.getStacktrace() in `a()` is fine
Thread.getStacktrace() in `b()` has wrong line number

This issue was already raised in [jetbrains](https://youtrack.jetbrains.com/issue/KT-8628/Line-numbers-are-incorrect-in-exception-stack-trace) (Third Party Problem), [openJdk](https://bugs.openjdk.org/browse/JDK-4972961) (Won't Fix) and [others](https://github.com/robstoll/atrium/issues/505), without fixes

I'm not sure it's a bug of Sentry, as it is a "missing feature" in the jdk

**Comment by stefanosiano** [comment]
We can include it in our troubleshooting page in the docs
