### ISSUE TITLE
Be able to add more ERROR_TYPES_HANDLED_BY_DATA_FETCHERS for GraphQL

### ISSUE THREAD

**Issue by SalyczeQ** [getsentry/sentry-java#2953]
### Problem Statement

Hello,
sometimes you have your own inner graphQL errors which you want to ignore (something like access denied) and don't re-throw them as another runtime exception and log them.

### Solution Brainstorm

It would be nice to be able to add more ignored errors to `ERROR_TYPES_HANDLED_BY_DATA_FETCHERS` for GraphQL. It's in `SentryInstrumentation` class.

What do you think?

Best regards,
Dusan

**Comment by adinauer** [comment]
Hello @SalyczeQ I assume you've seen https://github.com/getsentry/sentry-java/issues/2899 as you've upvoted there. I'd like to close this issue as a duplicate in favor of the other one. Would you agree that would solve your needs as well? Would you prefer ignored types to be set as a `List<String` instead of `List<ErrorClassification>`?

**Comment by SalyczeQ** [comment]
Hello @adinauer, I double check the issue which I am hading and #2899 would really solve the issue. Now I hot fix the issue with remapping error type to `graphql.ErrorType.DataFetchingException`, which is already statically ignored.

I think that `List<String>` give you more freedom. But more type strict` List<ErrorClassification>` would be still enough also for my case. 👍

**Comment by adinauer** [comment]
Closing this in favor of #2899 . Added a link to this issue on #2899 so we keep this feedback in mind - thank you!
