### ISSUE TITLE
Sentry can't catch stack/buffer overflow problem?

### ISSUE THREAD

**Issue by wingorithm** [getsentry/sentry-java#2988]
### Gradle Version

8.3

### AGP Version

8.1.2

### Code Minifier/Optimizer

R8

### Version

3.12.0

### Sentry SDK Version

6.30.0

### Steps to Reproduce

first of all i'm not sure if the Sentry SDK Version either 6.30.0 or not when using 3.12.0 (AGP). (can't find how to check it)

Case : i'm doing benchmarking for sentry self-hosted with android studio, one of my test is "stack overflow" error. it basically calling recursion function with no end like buffer overflow. But when the app stopped and forced closed, sentry didn't catch any error report?

to reproduce:
1. just simply call endless recursion function 

stackoverflow()
...
...
private fun stackOverflow() {
        stackOverflow()
}

### Expected Result

Sentry report the error 

### Actual Result

no report

**Comment by romtsn** [comment]
Hi @wingorithm, thanks for the report, we'll have to look into this and come back to you wrt further steps

**Comment by wingorithm** [comment]
ok, waiting for good news then...

**Comment by romtsn** [comment]
hi @wingorithm it is indeed not working, I've just tested it - the reason is payload size, because there are too many repeating frames and it's exceeding the limits. We should probably cap the max. number of repeating frames for such cases. I will check with team internally and provide a fix most likely, thanks for reporting the issue!
