### ISSUE TITLE
Implement handleException method in SentryGenericDataFetcherExceptionHandler

### ISSUE THREAD

**Issue by jrogers** [getsentry/sentry-java#3017]
### Integration

sentry

### Java Version

17

### Version

6.3.2

### Steps to Reproduce

With graphql-java 21.2 (which is version now used in DGS 8), the deprecated method onException was removed from the `DataFetcherExceptionHandler` interface. In order to be compatible, my suggestion is that sentry-graphql implements the handleException method in `SentryGenericDataFetcherExceptionHandler` as well as onException to be compatible.

### Expected Result

Exception handler works as intended with latest graphql-java

### Actual Result

`Execution java.lang.AbstractMethodError: Receiver class io.sentry.graphql.SentryGenericDataFetcherExceptionHandler does not define or inherit an implementation of the resolved method 'abstract java.util.concurrent.CompletableFuture handleException(graphql.execution.DataFetcherExceptionHandlerParameters)' of interface graphql.execution.DataFetcherExceptionHandler.`

**Comment by adinauer** [comment]
Thanks for opening this issue @jrogers we'll improve compatibility - can't give an ETA at this point.
As a workaround, can you copy the code in `SentryGenericDataFetcherExceptionHandler` into a new class where you implement the now required method, so you're not blocked? Then register that as a `@Bean`.

**Comment by adinauer** [comment]
What we've found out so far:

Starting with Spring-Boot `3.1.0` there is an exception instead of a log message, when a filter is already present in the ServletContext (https://github.com/spring-projects/spring-boot/pull/33911). I've not been able to get rid of the problem with `3.1.3`. Only when using  `3.0.12` and older as well as `3.2.0-RC1` and newer worked.

https://github.com/spring-projects/spring-boot/blob/dbe882aced8656b41d673b2542256c227bc528cd/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/servlet/DynamicRegistrationBean.java#L113-L125

In case of an embedded Tomcat, as used when running `bootJar`, `SentrySpringServletContainerInitializer` is not being used. With a dedicated Tomcat however it is being used. This combined with `SpringBootServletInitializer` which I extended in `SentryDemoApplication` causes the duplicates to surface. I presume this has always been the case but only now results in an exception.

Our hunch says, embedded tomcat sets some flag differently to ignore `src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer`. We're trying to find out more here. Help appreciated.

**Comment by adinauer** [comment]
It looks like starting with `3.2.x` Spring adds filters first and only then `SentrySpringServletContainerInitializer` is called.

**Comment by adinauer** [comment]
Sorry the deleted messages were intended for another issue.

**Comment by jrogers** [comment]
I just ended up forking both `SentryGenericDataFetcherExceptionHandler` and `SentryGraphqlExceptionHandler` for now...
