### ISSUE TITLE
Profile whole app startup

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-java#3039]
### Description

We want to understand how early we can start the profiler, so that we can profile the whole app startup process. This is related to the Starfish project.
This is just an investigation, that hopefully will end up with a POC.

**Comment by romtsn** [comment]
Just dumping it here since I did a bit of research prior:
* There's a method which is hidden (but I believe we can call it via reflection), that allows starting method tracing in streaming mode, which will directly stream to the provided file descriptor  https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/os/Debug.java;l=1373-1385
* If we'll be able to start profiling in streaming mode, ART will actually automatically restart profiling right after creating an app process https://cs.android.com/android/platform/superproject/main/+/main:art/runtime/native/dalvik_system_ZygoteHooks.cc;l=368-409?q=nativePostForkChild
  * In theory this will not capture the initial app startup (because we hadn't started profiling in streaming mode yet), but all the subsequent startups should be captured, which is probably a good start already.

**Comment by romtsn** [comment]
@stefanosiano this can be closed now right?

**Comment by romtsn** [comment]
Closed by #3101
