### ISSUE TITLE
How to specify the transport for a custom build

### ISSUE THREAD

**Issue by glennra** [getsentry/sentry-java#3229]
### Problem Statement

I want to make a custom build of sentry-native for Android so I can incorporate  Qt integration.

The comment [here](https://github.com/getsentry/sentry-java/issues/1626#issuecomment-887777490) implies that it is only a simple matter of enabling the Qt integration, which is done with a CMake config variable. This works after making sure the correct NDK and Qt versions are used by the build.

However the transport defaults to "none" and when linked to the app the library doesn't deliver any messages.

What is the recommended way to enable the transport for sentry-native on Android and how is it configured?

**Comment by adinauer** [comment]
@markushi can you help out here?

**Comment by markushi** [comment]
Hey @glennra, thanks for reaching out!

In our default setup the Android SDK takes care of being the transport. This roughly works the following way:
1. The Android SDK initializes the NDK [here](https://github.com/getsentry/sentry-java/blob/main/sentry-android-ndk/src/main/jni/sentry.c#L240), setting an outbox path, were all "native" events are simply written to disk
2. Whenever a native event or crash happens, `sentry-native` creates a file in the outbox path
3. The Android SDK watches the outbox path for changes, reads the files, enriches them and sends them to sentry

There could be multiple reasons why it's not working for you right now, but you can check the following:
* Your NDK init configuration, in case you're rolling your own
* Does `sentry-native` write down envelopes to disk?
* Does the Android SDK pick up the files?

Enabling `debug` should print some useful logcat messages to find the root cause:
```kotlin
SentryAndroid.init(context) {
    it.dsn = "..."
    it.isDebug = true
}
```

**Comment by glennra** [comment]
Thanks @markushi this was what I needed to know. To get it working I've called the above via JNI from C++.
The issue I've had is that in a Qt mobile app the entry point is in C++ and the way Qt Android apps are built is different to the standard way and the documentation is sparse.
