### ISSUE TITLE
Missing documentation leads to uncertainty 

### ISSUE THREAD

**Issue by leo-beliakov** [getsentry/sentry-java#3407]
### Problem Statement

What's the difference b/w event.unhandledException and event.throwable?
If even.isCrashed == true, does it always mean that event.throwable != null ?

I can't find this information anywhere in official docs 

![image](https://github.com/getsentry/sentry-java/assets/138994066/04bd80ea-4eb4-4bc6-8399-fa6d80bf1b12)

**Comment by romtsn** [comment]
Hi, the difference is that:
* `throwable` is the original `java.lang.Throwable` that this event was instantiated with. It can be any Throwable (also handled/checked exceptions)
* `unhandledException` is a `SentryException` type with `mechanism.handled=false`, and it's extracted from the `Throwable` above.

if `isCrashed = true`, then both `throwable` and `unhandledException` should not be null that's correct! Frankly speaking though, I think we'll hide `unhandledException` from public, because it's meant for internal use only. What is your usecase for these actually?

**Comment by leo-beliakov** [comment]
@romtsn thanks for your explanation 👍 

My case is that I want to send crash reports to my analytics provider as well:
<img width="457" alt="image" src="https://github.com/getsentry/sentry-java/assets/138994066/1027e82a-b22c-4223-b058-55c8410930ce">
 
So I was just wondering whether I should use throwable or unhandledException and if there's any difference b/w them 
Now it's clear, thanks!
