### ISSUE TITLE
Automatic breadcrumb support for Android

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#347]
Hopefully there's a way to hook into Android events globally. I think on iOS we do "Method Swizzling" which is apparently monkey patching but for Obj-C...

If anyone knows more on this I'd love to hear it.

**Comment by Hazer** [comment]
There are some, I don't know what kinds of events do you plan to catch, but looking at the Docs there says: 

> If called this will track every action sent from a Storyboard and every `viewDidAppear` from an `UIViewController`

So, to get every `onResume` from an `android.app.Activity` which roughly we translate to `viewDidAppear` from `UIViewController`:
- We can use [`Application.ActivityLifecycleCallbacks`](https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks.html) (someone's [sample code](https://gist.github.com/kblade/57c73fafa15e8b94c85c)). So if you initialize Sentry on `android.app.Application` (that's what I believe is the right thing to do), you can receive `Application` as argument and then call to register.

In Android we have another kind of `UIViewController` in iOS when we need an "Child" ViewController we just use an `UIViewController` inside another. In Android we use an `Fragment`. And there's quite a LOT of usage so that it cannot be ignored. But...
- Since 25.2.0 version of the Support Library, there's a new Callback for `Fragment`'s [`FragmentManager.FragmentLifecycleCallbacks`](https://developer.android.com/reference/android/support/v4/app/FragmentManager.FragmentLifecycleCallbacks.html) (someone's stackoverflow [sample](http://stackoverflow.com/a/42426058))
- If the user don't use Support Library, only [in Android O we will get a similar Callback](https://developer.android.com/reference/android/app/FragmentManager.FragmentLifecycleCallbacks.html)
- As you can see in the above sample, as far as I understood, each `Activity` will need to register the `Fragment`'s Callback for Breadcrumb, it is so magical as for `Activities` and `UIViewControllers`. For this _limitation_ I believe we could use `Application.ActivityLifecycleCallbacks` again.
- During `ActivityLifecycleCallbacks.onActivityCreated` callback we can call for ex: `activity.getSupportFragmentManager().registerFragmentLifecycleCallbacks(provideSentryFragmentBreadcrumbCallbacks())`. Now, we are doing it like magic again.

And finally maybe some Java Reflection to get something else.

Hope it helps.

**Comment by bretthoerner** [comment]
Thanks for all this, I'll check it out soon.

**Comment by Hazer** [comment]
@bretthoerner Looking further into it, I am thinking that we can use a ContentProvider to set the ` Application.ActivityLifecycleCallbacks` to the `Application` during startup. When I got some working code I will share it in a gist or maybe a pull request.

**Comment by sheelaknaik** [comment]
Hi, can you please share an sample for this?

**Comment by k4biri** [comment]
Any news on this matter? 😄

**Comment by marandaneto** [comment]
Hey folks, there's a brand new Android SDK that is in release candidate already and it will be stable very soon.

This feature will land in there.

Please have a look at https://github.com/getsentry/sentry-android
Feedbacks are very welcomed, thanks :)

Stay tuned.

**Comment by marandaneto** [comment]
@k4biri please, have a look at https://github.com/getsentry/sentry-android#blog-posts
one of the blog posts tells how to create an integration for that.

**Comment by marandaneto** [comment]
getsentry/sentry-android/issues/210
