### ISSUE TITLE
Metrics Stopped reporting in 7.9.0

### ISSUE THREAD

**Issue by tjerkw** [getsentry/sentry-java#3472]
### Integration

sentry

### Java Version

eclipse-temurin:11-jre

### Version

7.9.0

### Steps to Reproduce

Implement metrics with 7.8.0, it works:

```
 Sentry.metrics().increment(
                counter.key,
                value.toDouble(),
                null,
                attributes,
            )
```

Then upgrade to 7.9.0, and now metrics are only sent once per day, instead of when they happen.

### Expected Result

When a metric is recorded it should be send to the server. 

Now we only receive 3 metrics every 24 hours.. Instead of 20 metrics in realtime. 

### Actual Result

Metrics are not showing up in realtime, and a lot of them are dropped.

This is the configuration:

```
  Sentry.init { options ->
                options.dsn =.... (the correct DSN)
                options.release = "1.0"
                options.environment = "DEV"
                if (!SystemEnvironment.environment.isLive) {
                    options.isEnableMetrics = true
                }
            }
```

**Comment by stefanosiano** [comment]
hi @tjerkw 
Can you confirm the metrics are sent correctly if you downgrade the SDK to version `7.8.0`?
Also, can you enable `options.isDebug = true` and attach a log when the metric should be sent, please?

**Comment by andorkerti** [comment]
Hi @stefanosiano 
I can confirm. After downgrade the metrics are sent normally.
With version 7.9.0 only the first metric are sent (after startup).
As I read the code I suspect the problem is in the MetricsAggregator.java:
the flushScheduled variable is set to true during the first add() call @ 277 and it never set to false so the schedule function is never called again @ 229 therefore the flush() will run only once in the lifetime of the MetricsAggregator
