### ISSUE TITLE
How to reproduce warm start?

### ISSUE THREAD

**Issue by zhukic** [getsentry/sentry-java#3635]
### Description

Hello!

I'm trying to attach custom child spans to the warm start span as well as for [the cold start](https://github.com/getsentry/sentry-java/issues/3581).

The question is how to reproduce the warm start on a device? 
I tried to set "No background processes" in developer options but it didn't help.

**Comment by zhukic** [comment]
@stefanosiano Hello!
Sorry for disturbing you. Could you please help here?

**Comment by stefanosiano** [comment]
hi @zhukic 

> I tried to set "No background processes" in developer options but it didn't help.

This actually kills background processes, so whenever you open the app, it will restart the process again, leading to a cold start.

Warm starts are difficult to simulate, as they depend on the system.
You can try to back out of the app and open it again, as explained in the [official docs](https://developer.android.com/topic/performance/vitals/launch-time#warm). Or you can try to keep a foreground service running when you finish the activity and then open it again.
Beware that since Android 12 the [back button does not finish root activities](https://developer.android.com/about/versions/12/behavior-changes-all#back-press) anymore, so you may have to manually call `finish()`

**Comment by zhukic** [comment]
@stefanosiano thank you for the answer!

**Comment by zhukic** [comment]
[This](https://github.com/getsentry/sentry-java/issues/1950#issuecomment-1067587818) solution helped
