### ISSUE TITLE
Appengine module stores state in instance memory

### ISSUE THREAD

**Issue by stickfigure** [getsentry/sentry-java#427]
AppEngineAsyncConnection appears to store critical state in instance memory; when a task executes on a different instance, it will not find the state and drop the message.

Unless I'm wildly misreading this code, there's no way this can possibly work. GAE spawns lots of instances and cycles them frequently. Tasks are executed on random instances.

**Comment by bretthoerner** [comment]
Yeah, looking at the code, that does seem broken. I didn't realize `DeferredTask` was like an "external" call (or could be). I'll admit the AppEngine integration is very broken, I'm surprised you got as far as this issue, I'm wondering why you didn't hit this? https://github.com/getsentry/sentry-java/issues/228

Anyway, fixing AppEngine is on my list. It's good to know people are trying to use it (sorry!) because I honestly wasn't sure where to prioritize this.

I would love PRs, though, too. :)

**Comment by stickfigure** [comment]
I haven't tried it; I was just checking out the code to see how you approached the problem, since you can't intercept logging on GAE/Standard (or at least, I never found a way).

Some time ago I wrote a "good enough" adapter for Rollbar (https://github.com/stickfigure/rollbar-appengine) that just captures exceptions. I'm thinking of using Sentry instead for a new project; I'll try forking rollbar-appengine and converting the submit code.

I suspect the only really good solution is to write an slf4j binding that intercepts and forwards on to the j.u.l binding. Well, good for people that use slf4j.

**Comment by bretthoerner** [comment]
Hmm, we so have jul/slf4j bindings. I *think* the stuff in #228 (and there is even a very outdated PR where I handled most of it) is what's needed to make everything work. I'd love input if that's incorrect, though.

Can you remind me why AppEngine uses the weird deferred stuff, is it that you can't use background threads? One (suboptimal) solution is to use the plain Sentry client but disable async so the event is sent on the current thread. If that works it at least proves we have a decent starting point, since I wouldn't recommend reimplementing/maintaining all the stuff we do in our Java SDK.

**Comment by stickfigure** [comment]
Hmmmm, if `Logger.getLogger("").addHandler(...);` is allowed, seems like it should be possible to make this work. It would be better than intercepting at a layer between slf4j and j.u.l. Maybe I'll take a stab at it, although it might not be for a couple weeks.

Yeah, background threads are not allowed in GAE/Standard, nor is writing to the filesystem. GAE boils an app down to a handful of primitives; the "do something async" primitive is the task queue. It's lightweight, persistent, easy to monitor, and has nice management facilities like throttling and exponential backoff. IMHO it works pretty well for this use case. The alternative is what you've done: implemented an unmonitored persistent queue using threads and local ephemeral disk. Even if your implementation is perfect, most won't be, so it's nice to have the queue as a standard service.

**Comment by wholegroup** [comment]
@bretthoerner @stickfigure GAE/Standard now supports Java 8 (beta) and there is possibility to use  Java's built-in API to create threads. Also [the documentation](https://cloud.google.com/appengine/docs/standard/java/runtime-java8) says "Doesn't impose a security manager as the Java 7 runtime does, which means your code won't be restricted by Java permissions issues."

**Comment by bretthoerner** [comment]
Awesome, thanks for the info.

Do you know if this is the new default for all projects (and so we can depend on it), or do people have to manually upgrade?

**Comment by wholegroup** [comment]
@bretthoerner Java 8 support currently is in beta mode, by default new projects still use Java 7. But users can migrate their projects easily as I did (just to add `<runtime>java8</runtime>` into `appengine-web.xml`). 

Also I've tried to use the standard factory (not `AppEngineSentryClientFactory`), but got errors:
```
Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager
```

It appears because my application is free and GAE/Standard doesn't allow to use native network classes `URL.openConnection and related methods`. Instead of this GAE uses URLFetchAPI that doesn't work with native threads.
Probably for paid applications the standard factory works well.

p.s. I've finished migration from raven to sentry library right now. It works well with `AppEngineSentryClientFactory`. There is only one issue, I can't change an error level via `logging.properties` (this method doesn't work on GAE/Standard) nor `sentry.properties`. I would be glad if you add new parameter `level` into sentry.properties.

**Comment by bretthoerner** [comment]
Weird, what level is it stuck at then? So there's no way to change the level at all in AppEngine?

**Comment by wholegroup** [comment]
In AppEngine **Standard** you should to add `SentryHandler` in runtime, because there is no way to add any handlers via`logging.properties`. That's why `io.sentry.jul.SentryHandler.level=` doesn't work and I have to set a log level in runtime.

I do it in a listener:
```java
public final class LogHandlerConfig implements ServletContextListener {

    @Override
    public void contextInitialized(final ServletContextEvent sce) {
        if (SystemProperty.environment.value() == SystemProperty.Environment.Value.Production) {
            final SentryHandler sentryHandler = new SentryHandler();
            sentryHandler.setLevel(Level.WARNING);
            Logger.getLogger("").addHandler(sentryHandler);
        }
    }

    @Override
    public void contextDestroyed(final ServletContextEvent sce) {
    }
}
```

but the Sentry library should work well and without `AppEngineSentryClientFactory` out from the box in AppEngine **Flex**.

**Comment by wholegroup** [comment]
@bretthoerner @stickfigure 
About this issue. As I see `AppEngineAsyncConnection` serializes Event object when creating a new task. Could you show in the code what exactly do you mean?

> AppEngineAsyncConnection appears to store critical state in instance memory

**Comment by stickfigure** [comment]
As a longtime GAE user: Please don't start threads, it's not the appengine way - not even with Java8. Just put a DeferredTask on the task queue that makes the remote call. Task queues can be throttled so that a bad code push won't suddenly fill up my sentry quota for the month. They're persistent. They're reliable. They're easy to monitor with the builtin stackdriver tools.

**Comment by maciejwalkowiak** [comment]
AppEngine module has been deprecated.
