### ISSUE TITLE
Configuring user context question

### ISSUE THREAD

**Issue by mikebell90** [getsentry/sentry-java#448]
Re #443  I have another question

I now have some code doing

```
try {
     // blah blah  - build using userbuilder
    Sentry.setUser(user);
} catch (Exception e) {
  log ("oops", e)
}
```

So two questions

1. Is it safe to do this even when Sentry is disabled (eg not referenced in log4j.properties). This will be the case in local environments for example. Is there way to check?

2. If that did throw an exception the log won't FOOBAR by hitting sentry right after will it? ;)

**Comment by bretthoerner** [comment]
1. With no appender setup (or even with an appender, but no DSN provided) Sentry will default to a client that no-ops for everything, so it should be completely safe. If you find otherwise that's a bug I'd like to fix.
2. I'm not sure what you mean by it FOOBARing? If Sentry isn't configured it will do nothing, if it is configured the Sentry appender will asynchronously (by default) send the event to Sentry. The SDK shouldn't ever throw an exception (unless you attempt to configure it and do so incorrectly, like with an invalid DSN).
