### ISSUE TITLE
Add breadcrumb threshold option for logging

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#450]
If threshold is not set: every log message to the appender becomes an event.

If threshold is set: messages `<` the threshold are set as breadcrumbs, messages `>=` the threshold are real events.

**Comment by mjgp2** [comment]
Hey - is there any update on this? It's really necessary to make the most of the integration

**Comment by marandaneto** [comment]
hey @mjgp2 :)
Which integration are you working with?

if log4j2, I believe you could do something like https://docs.sentry.io/clients/java/integrations/#usage-4
if logback, https://docs.sentry.io/clients/java/integrations/#usage-5

does that help?

**Comment by brandonlenz** [comment]
@marandaneto I think the main issue is that development teams aren't going to use traditional logging as well as the somewhat verbose BreadCrumb syntax. It's a duplication of work.

Right now you can configure the level at which events should be sent to sentry via the appender. In the event of an error, you probably want all the debug logs leading up to the error displayed as breadcrumbs in the error event. That would be huge.

It isn't worth sending events for all debug logs, and they wouldn't be useful as separate events due to the intention behind how sentry aggregates and displays events. But debug logs _are_ very valuable when packaged with the ultimately resulting error event (as breadcrumbs as this issue request suggests)

**Comment by marandaneto** [comment]
Sentry-Java SDK v3 and its integrations have a breadcrumb threshold
