### ISSUE TITLE
Is lockdown the same as rate limiting?

### ISSUE THREAD

**Issue by tklovett** [getsentry/sentry-java#469]
Our service has seen some LockedDownExceptions:
```
2017-07-24 14:31:26.231 WARN 7 --- [pool-1-thread-1] com.getsentry.raven.Raven.lockdown : The connection to Sentry is currently locked down.
    com.getsentry.raven.connection.LockedDownException: Dropping an Event due to lockdown: Event{...}
```

I can't find any references to "lockdown" in Sentry docs or user forums, its a concept that appears to only exist in `sentry-java`. Is "lockdown" the same as rate limiting as documented on `help.sentry.io` and `sentry.io/organizations/{org}/stats/`?

**Comment by bretthoerner** [comment]
Yeah, it's an odd naming convention (that dates way back to this being a community-build SDK).

The lockdown exists solely on the client-side and prevents spamming the Sentry server when a previous send raised an exception.

You should have a log line starting with "An exception due to the connection occurred, a lockdown will be initiated." that comes with a chained exception giving the cause for the lockdown. A common cause is receiving a backoff reply from the server with a `Retry-After` header, as you've mentioned.

**Comment by tklovett** [comment]
Ah ok, so a lockdown does differ slightly from the rate-limit in that its enforced by the client rather than the API -- but still based on the API's given `Retry-After` time.

👍  thanks for the info!
