### ISSUE TITLE
setUser deprecated

### ISSUE THREAD

**Issue by fab1an** [getsentry/sentry-java#473]
`Sentry.setUser` is marked deprecated, but there is no information how to replace it?

**Comment by bretthoerner** [comment]
Sorry, I thought IDEs would provide help to pull [this](https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/Sentry.java#L195) out.

In short, all you need to do is `Sentry.getContext().setUser(u);`.

I'm trying to move all "context-specific" methods onto the context itself, so that it's clear what is and isn't context.

**Comment by fab1an** [comment]
Thank you, Android Studio doesn't:

![screen shot 2017-07-26 at 15 46 22](https://user-images.githubusercontent.com/55547/28624518-a6f7b744-7219-11e7-9650-c8884fafa969.png)
