### ISSUE TITLE
Same Transaction In Every Log

### ISSUE THREAD

**Issue by sidhant92** [getsentry/sentry-java#504]
Im using sentry-logback to log my events in sentry. But in every event i track the transaction is coming out as:
akka.event.slf4j.Slf4jLogger$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogger.scala:72)

Why is this happening?

**Comment by bretthoerner** [comment]
Hmm, can you link me to an event on `sentry.io`?

**Comment by kaarelnu** [comment]
I'm experiencing the same issue. I'd be keen to understand the reason.

**Comment by bretthoerner** [comment]
Can you link me to an event?

My guess here is Akka does takes over logging by sending it to a different actor, and so the stacktrace is exactly the same for every single message logged... which completely breaks grouping. Not sure how we can handle that other than disabling that part of Akka somehow?

**Comment by kaarelnu** [comment]
Can you access this: https://sentry.io/dpipe/api-service/issues/371663383/events/8093636652/ ?

**Comment by bretthoerner** [comment]
Thanks! I'm Sentry staff, so yup. Let me do some digging.

**Comment by bretthoerner** [comment]
OK, Akka must be doing something abnormal that messes us up here: https://github.com/getsentry/sentry-java/blob/master/sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java#L146-L150

**Comment by bretthoerner** [comment]
Fix in PR at #520. Thanks for reporting this.

**Comment by bretthoerner** [comment]
Can y'all try out version `1.6.0` (syncing to Maven Central now) and let me know if it doesn't work for you?

**Comment by Alireza-Farahani** [comment]
I tested the sentry-logback v 1.6.8 and it still puts all logs in a method in same group. (Even with different messages or parameterized message). If an exception is passed along with the log, exception type is used in grouping but again message is ignored

**Comment by bretthoerner** [comment]
Hmm, can you link some example events on Sentry?

**Comment by Alireza-Farahani** [comment]
Sorry for late response,
[example event](https://sentry.io/share/issue/d28fc15a3c2a48c9a71860d66d647a7a/)
and [github project](https://github.com/Alireza-Farahani/sentry-logback-test):

I think grouping all messages in logback occurs because it includes StackTrace for all messages and sentry priorities the StackTrace over log message.

**Comment by Alireza-Farahani** [comment]
Is there a way in logback to send events without Stacktrace?

**Comment by bretthoerner** [comment]
Not currently, I think the assumption right now is *either*:

1. Different exception classes are being logged.
2. If the same exception is used, it is being thrown from different methods so it can be differentiated.

A hack around this is to create simple named `private void logThatXHappened()` type methods so that the stacktrace differs.

I'm open to ideas, but sadly we can't just go by line number because that would mean minor changes to the codebase would make all errors group into different issues.

**Comment by marandaneto** [comment]
grouping rules can be set on SDK or server-side https://docs.sentry.io/platforms/java/data-management/event-grouping/
