### ISSUE TITLE
Not compatible with Spring Session

### ISSUE THREAD

**Issue by sudokai** [getsentry/sentry-java#509]
SentryServletRequestListener stores the raw request too early before it passes through Spring's DelegatingProxyFilter. Hence it's impossible to add any user data stored in sessions to the events, because Sentry can't access the session managed by Spring.

Could you provide an alternative hook, such a Filter, instead of a ServletRequestListener?

Thank you in advance.

**Comment by bretthoerner** [comment]
That seems reasonable. Will probably need to handle #494 as part of this too.

I'll try to get time for this but I'm not positive when this will happen. PRs always welcome in the meantime if anyone has interest. :)

**Comment by fprochazka** [comment]
I had the same problem. Since I have a custom filter that wraps the request in content-caching wrapper (so the body's content can be read multiple times) and wanted to report also the request body, I had to write this. It's not very nice to get the request from `RequestContextHolder`, but the `SentryServletRequestListener` is mostly static too, so what the heck...

```java
public class HttpEventBuilderHelper implements EventBuilderHelper
{

    private static final Logger log = LoggerFactory.getLogger(HttpEventBuilderHelper.class);

    private final RemoteAddressResolver remoteAddressResolver;

    public HttpEventBuilderHelper()
    {
        this.remoteAddressResolver = new ForwardedAddressResolver();
    }

    @Override
    public void helpBuildingEvent(final EventBuilder eventBuilder)
    {
        HttpServletRequest servletRequest = getHttpRequest();
        if (servletRequest != null) {
            eventBuilder.withSentryInterface(new HttpInterface(
                servletRequest,
                remoteAddressResolver.
                IOUtils.toString(servletRequest.getReader())
            ));
        }
    }

    private HttpServletRequest getHttpRequest()
    {
        try {
            RequestAttributes requestAttributes = RequestContextHolder.currentRequestAttributes();
            return HttpServletRequest.class.cast(requestAttributes.resolveReference(RequestAttributes.REFERENCE_REQUEST));

        } catch (IllegalStateException e) {
            log.warn(e.getMessage(), e);
            return null;
        }
    }

}
```

**Comment by kailt** [comment]
Doesn't work for me. I don't use Spring as a whole, only Spring Session and RequestContextHolder.currentRequestAttributes() always throws an IllegalStateException.

Thank you for sharing the snippet though.

**Comment by pioto** [comment]
Thanks, I'm also seeing this issue. I have Spring Security providing for authentication in my application.

In my app code, right before my `log.error(...)` call, I can look a the `HttpServletRequest`, and `request.getUserPrincipal()` does return the expected `Principal` with the authenticated username, etc.

I can also access that authentication via `SecurityContextHolder.getContext().getAuthentication()` when I pause my debugger in `io.sentry.event.helper.HttpEventBuilderHelper#addUserInterface`.

But, within that same method, `servletRequest.getUserPrincipal()` returns `null`.

I think the issue may be that Sentry is using this to get the ServletRequest, which may be grabbing a copy of it before Spring Security enriches it:

```java
HttpServletRequest servletRequest = SentryServletRequestListener.getServletRequest();
```

I'm not sure what the best way to handle this would be, but a few options occur to me:

* Rework the `SentryServletRequestListener` to be a `Filter` instead, and ensure it gets added to the filter chain after Spring Security, so that it can grab onto the enriched `HttpServletRequest`. That seems to be the preferred solution above, has anyone attempted implementing that?
* Keep this code as-is, but add an additional `SpringSecurityEventBuilderHelper`, which calls `org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication()` directly, and if the returned `org.springframework.security.core.Authentication` is not null, uses `authentication.getName()` to set the username for the event. That looks somewhat like the solution provided by @fprochazka above, but I'm not 100% clear on how he gets that wired into Sentry?

**Comment by pioto** [comment]
This also doesn't appear to be specific to Spring Session -- I've ensured I have no Spring Session libraries in my classpath, and I still see this issue.

**Comment by marandaneto** [comment]
@maciejwalkowiak is this still relevant?

**Comment by maciejwalkowiak** [comment]
@marandaneto we need to first verify if this is still an issue with new SDK

**Comment by maciejwalkowiak** [comment]
In addition to a servlet request listener, we have now `SentrySpringFilter` and `SentryUserFilter`, so the issue can be closed.
