### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#527]
Looks like it has been released. We need to add module support: http://blog.headius.com/2017/10/migrating-to-java-9-modules-maven-osgi.html

**Comment by bretthoerner** [comment]
Not yet, I could try to look into it soon. Are you trying to use Sentry with Java 9 modules @kashike ?

**Comment by kashike** [comment]
I'm working on trying to move some applications to Java 9, and going through my large list of dependencies to ensure they're ready.
No rush, but it would be nice to get this sooner than later - especially since simply adding an `Automatic-Module-Name` to the manifest will work until this project becomes an *actual* module.

Related:
https://github.com/google/guava/pull/2846
https://github.com/google/guava/pull/2961
https://github.com/vigna/fastutil/issues/89#issuecomment-361202718

**Comment by bretthoerner** [comment]
PR for basic support at #551 if you don't mind reviewing it @kashike, thanks!

**Comment by adinauer** [comment]
Somewhat related to https://github.com/getsentry/sentry-java/issues/527
