### ISSUE TITLE
log4j: simple string events without exception are all grouped together

### ISSUE THREAD

**Issue by freewil** [getsentry/sentry-java#534]
Quote from https://docs.sentry.io/learn/rollups/
> If a stacktrace or exception is involved in a report, then grouping will only consider this information.

The problem is I am working with an app that has many simple string logs without an exception, such as `logger.error('something happened')` and Sentry is grouping these all together, even if they have different logger names.

So the stacktrace sent to Sentry looks like this:
```json
{
  "sentry.interfaces.Stacktrace": {
    "frames": [
      {
        "function":"error",
        "abs_path":"SLF4JLog.java",
        "module":"org.apache.commons.logging.impl.SLF4JLog",
        "in_app":false,
        "lineno":200,
        "filename":"SLF4JLog.java"
      }
    ],
    "registers":null,
    "frames_omitted":null
  }
}
```

Here is the relevant block of code:
https://github.com/getsentry/sentry-java/blob/4c04233353b9537a235ec1883280dd233f86556a/sentry-log4j/src/main/java/io/sentry/log4j/SentryAppender.java#L119-L125

I'm not sure in what cases/environments where that would not always just be a location in the apache log4j package. If there are valid cases for that, I think we should check whether the location is from the log4j package and just leave the stacktrace empty in that case.

Also see:
https://forum.sentry.io/t/feature-request-include-logger-in-issue-signature/1432

**Comment by bretthoerner** [comment]
I do agree that block looks suspect. I'll have to dig a little to see if it seems safe to remove.

---

Another issue is that deciding when to group (and not group) simply by message is impossible for us since we have no other context.

People don't want these to group:
`Error Foo happened.`
`Error Bar happened.`

But they do want these to group:
`Error, couldn't find user bob`
`Error, couldn't find user jane`

So we really encourage people to send exceptions. Especially because the stacktrace is useful when you're trying to understand the location on Sentry. Have you considered throwing and catching an exception in these cases?

**Comment by freewil** [comment]
> Have you considered throwing and catching an exception in these cases?

Yes - I'm doing some work around this now, I've been doing some experimenting with adding exceptions and/or doing some custom fingerprinting. Will try to update this if I have anything insightful to share.

**Comment by freewil** [comment]
Luckily we were using a custom logger that simply wrapped around log4j, so it made it quite easy to change the definition of `logger.error(String)` to also include an Exception in the second param, so we always have a stacktrace. That is working quite well and would recommend anyone to try this first rather than try to implement custom fingerprinting.

**Comment by bretthoerner** [comment]
Awesome, thanks for the update. And yeah, Sentry isn't really meant for plain logs, so I'm glad you were able to find a solution that includes a stacktrace.
