### ISSUE TITLE
stacktrace.app.packages property is being ignored

### ISSUE THREAD

**Issue by UgVaDevLabs** [getsentry/sentry-java#634]
I keep sentry.properties file in a project root directory and it looks something like this:

```
defaults.project=project-name
defaults.org=project
auth.token=MyAuthToken
stacktrace.app.packages=com.myapp.examplePacakge
```
But I still get these warnings

>  No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames [main]
> 10:23:04.617 WARN  io.sentry.a - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames [main]

I event tried to disable the stacktrace.app.packages property using 

```
defaults.project=project-name
defaults.org=project
auth.token=MyAuthToken
stacktrace.app.packages=
```
But I still see the same warnings

**Comment by bretthoerner** [comment]
Where is `sentry.properties` at *runtime* for your application?

There is some confusion caused by us having a `sentry.properties` file that is used to configure the Gradle Plugin, and also having a `sentry.properties` file used to configure the Sentry SDK at runtime. The latter needs to be available in the current working directory *at runtime* (for example, when using `java -jar foo.jar` on a server) OR in the CLASSPATH at runtime.

In most server side applications the default directory to add resources to your classpath is `src/main/resources/`, and on Android the default is `app/src/main/resources/`. https://docs.sentry.io/clients/java/config/#configuration-via-properties-file

**Comment by UgVaDevLabs** [comment]
Thank you, I have managed to resolve this issue
