### ISSUE TITLE
Android R8 code shrinker support

### ISSUE THREAD

**Issue by audkar** [getsentry/sentry-java#662]
Sentry plugin is an only blocker for us to start using R8 code shrinker. 

Android Studio stable version 3.3 has been released with R8 under feature toggle. But next version of AS 3.4 is going to enable this by default. It would be very appreciated that until that this problem could be solved.

**Comment by nesterov-n** [comment]
I'm very interested in this feature too. I'm ready to help with R8 support and have some experience in android gradle plugin. It would be great if someone from maintainers described the main issues with android r8.

**Comment by ninniuz** [comment]
From what I understood the R8 version bundled with AGP 3.3.0 should already emit a mapping file that has the same format as the ProGuard one (it only includes some comment lines at the top of the file).
Unfortunately I could not try that on my project yet, could you @audkar ?

**Comment by nesterov-n** [comment]
Yes, R8 generates the mapping file. I'll be able to test sentry with r8 in a couple of weeks.

**Comment by ninniuz** [comment]
> @ninniuz I'm a developer on this project and probably won't be fixing this myself. Did you mention the wrong person?

Yes, I wanted to mention @bretthoerner 😃

**Comment by bretthoerner** [comment]
Have to loop in @mitsuhiko here for the Proguard server-side stuff, mostly because I'm actually out of paternity.

I'm curious though, without this LNO feature enabled can the existing R8 mapping file be uploaded to Sentry manually using the `sentry-cli` tool and does the desymbolification work? That'd be a good thing to figure out.

**Comment by ninniuz** [comment]
> I'm curious though, without this LNO feature enabled can the existing R8 mapping file be uploaded to Sentry manually using the `sentry-cli` tool and does the desymbolification work? That'd be a good thing to figure out.

From this sentence in https://issuetracker.google.com/issues/70776323#comment6
> If a map file is needed to understand stack traces, then line number optimization will also be turned on.

and from the relevant source code in https://r8.googlesource.com/r8/+/master/src/main/java/com/android/tools/r8/R8Command.java#673
I'd say LNO is turned off for release builds iff optimization and minification are both turned off.
If minification is turned off, though, there is no need for a mapping file since you won't have any obfuscated name in the resulting bytecode.

Apart from LNO, I think the R8 mapping file (when R8 is used in compat mode) is compatible with Proguard mapping file format, hence it should be possible to upload it with `sentry-cli` and desymbolification should work as-is.
(as a matter of fact, the current R8 mapping file, also with LNO on, is compatible with the latest Proguard retrace tool which uses this function in [`MappingReader`](https://sourceforge.net/p/proguard/code/ci/default/tree/core/src/proguard/obfuscate/MappingReader.java#l143))

**Comment by bretthoerner** [comment]
This is coming shortly via @bruno-garcia

**Comment by bruno-garcia** [comment]
We've added support for R8. It's getting deployed to sentry.io now.
It also requires the latest version of the `sentry-gradle-plugin` and/or `sentry-cli`.

**Comment by bretthoerner** [comment]
R8 support is in 1.7.20 thanks to @bruno-garcia 

https://github.com/getsentry/sentry-java/releases/tag/v1.7.20
