### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [getsentry/sentry-java#692]
I see there are release notes for 1.7.22 but no release on https://github.com/getsentry/sentry-java/releases 

How does the release process for this repository work? 
I can setup a build for 1.7.22 in our CI but would prefer to just use the official release.

Please let me know if there's a better place to ask questions like this.

**Comment by bretthoerner** [comment]
It's just manual based on changes/demand. If 1.7.22 would be helpful to you I can make a release.

**Comment by chris-smith-zocdoc** [comment]
Thanks @bretthoerner , should this be documented somewhere? Maybe the readme?

**Comment by bruno-garcia** [comment]
@chris-smith-zocdoc we've released [1.7.22](https://github.com/getsentry/sentry-java/releases/tag/v1.7.22) and [1.7.23](https://github.com/getsentry/sentry-java/releases/tag/v1.7.23).
The [changelog](https://github.com/getsentry/sentry-java/blob/master/CHANGES) is in the root of the repo and also in the release.

I hope the issue is addressed. If not, feel free to reopen if needed.
