### ISSUE TITLE
Where do you find uploaded mapping.txt for a release?

### ISSUE THREAD

**Issue by emitchel** [getsentry/sentry-java#730]
I recently integrated the upload mapping plugin for an Android project. Building the .apk shows the upload was successful but I'd like to see the mapping.txt _on the Sentry platform_ prior to releasing. Is there a way to view the mapping txt on Sentry for a given release? Or do I have to trust that the stack traces will be deobfuscated when new issues pop up on this new release? 

I wasn't able to find information around this, thanks in advance

Also - is `sentry-debug-meta.properties` manual creation necessary when using the plugin? I see  several issues around this properties file and it's not clear from the java integration doc that it's necessary when utilizing the plugin over manual upload.

**Comment by bruno-garcia** [comment]
You can see the mapping file under the project settings _Debug Files_:
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/1633368/60512059-dbbadd80-9cd3-11e9-8cbb-40d0b31fcdea.png">

If you need additional info on this, since this is general Sentry support (as opposed to an SDK issue), please refer to [support](https://sentry.io/contact/support/).

Regarding `sentry-debug-meta.properties`: Sentry Android Gradle plugin generates and copies this file to the apk automatically. There's no need to create it manually.
