### ISSUE TITLE
JNDI configuration

### ISSUE THREAD

**Issue by Paxa** [getsentry/sentry-java#789]
I use spark with jndi, and I keep seeing these messages:
```
JNDI not configured for Sentry (NoInitialContextEx)
```

Do I need to manually add some configuration?

**Comment by metlos** [comment]
This means that Sentry thinks JNDI is available by doing a quick check on the availability of the `InitialContext` class and, later on, it tries to look up configuration in JNDI and this trace message happens if Sentry is unable to instantiate the initial context (by default it just calls `new InitialContext()` on each config prop lookup).

So the question here is why is Sentry unable to instantiate the `InitialContext` in your environment - that very much depends on the configuration of JNDI and classloader arrangement in your application.

Alternatively if you don't use JNDI for configuring Sentry, you may think about providing sentry with a custom `Lookup` instance using `Sentry.init(SentryOptions.from(lookupInstance, ...))` and exclude the JNDI configuration provider from the lookup.

**Comment by marandaneto** [comment]
@bruno-garcia is this still relevant? one could configure sentry using either the options callback or a configuration file eg sentry.properties

**Comment by romtsn** [comment]
We're gonna close this as there was not activity for 3 years. Please feel free to reopen if there's still a demand.
