### ISSUE TITLE
Agent for Android

### ISSUE THREAD

**Issue by cromefire** [getsentry/sentry-java#801]
I don't know, if this is even possible, but it would be really nice to have the sentry agent also available for Android.

It looks doable, but hard (Xposed seems to have something similar at the first glance)

**Comment by cromefire** [comment]
(And the Android debugger is also capable of that)

**Comment by cromefire** [comment]
This might be interesting: https://source.android.com/devices/tech/dalvik/art-ti

**Comment by marandaneto** [comment]
@cromefire thanks for your message.

The Java Agent has been discontinued. See https://github.com/getsentry/sentry-docs/pull/1423

I've had a quick look at ART TI docs and it seems that this is only for debuggable releases, so it won't work on production releases.

We may have a deeper look at it, but if so, it will land in https://github.com/getsentry/sentry-android as it is our new Android SDK (still on Beta though), please raise an issue there if this is something that would be really desirable from your side, thanks.

**Comment by cromefire** [comment]
Is there any way then to get the locals with Java?

**Comment by marandaneto** [comment]
@cromefire well the Java Agent does it, I think it works on Android as well, the thing is, it's too slow, we would need to investigate a bit more and see how we can improve it afaik.

**Comment by romtsn** [comment]
@cromefire we've decided this is not viable for now due to the Java Agent being slow and ART TI only available in debug builds. If you're looking for local variables specifically a better path might be through bytecode manipulation using [ASM](https://stackoverflow.com/questions/50051393/asm-getting-local-variable-name-and-value-inside-a-method-of-a-class). We might look into this in the future, but gonna close this issue for now.
