### ISSUE TITLE
Correct way to check Sentry is logging?

### ISSUE THREAD

**Issue by piotrblasiak** [getsentry/sentry-java#836]
When I don't set a DSN, Sentry will complain with warnings but I need a way to check in code if Sentry is logging. Currently I have to do:

sentryHasValidDsn = Dsn.dsnLookup() != Dsn.DEFAULT_DSN;

Which feels hacky. Is there any other way to do this? I would expect Sentry.isInited() to perhaps return false in such a case.

**Comment by marandaneto** [comment]
@piotrblasiak what's the use case of not setting a DSN but still using Sentry?
an Empty DSN `""` will disable the SDK, so that might be also a workaround?

`Sentry.isInitialized()` indeed should return `false` IMO, let me check that.

cc @bruno-garcia do you know if this is a bug or is it purposely?

**Comment by bruno-garcia** [comment]
Sounds like a bug to me. Using DSN `""` should disable the SDK and indeed `isInitialized` should return false. It doesn't know because it means "Sentry.init was already called" but not necessarily the SDK was successfully initialized.

To change this would be a breaking change and we definitely don't want to bump `2.0` since that'll come from `sentry-core` next.

**Comment by marandaneto** [comment]
@bruno-garcia would make sense to add a `isEnabled()` which returns `true` if `isInitialized=true` AND `dsn != DEFAULT` AND `dsn != ""`? it seems hacky, just like @piotrblasiak did, but its not a breaking change.

**Comment by bruno-garcia** [comment]
@marandaneto That's a great idea. It is also something we have in the other SDK.

Would even be nicer to add a `@Obsolete` to `isInitialized` saying it'll be deprecated to help us move over to `sentry-core` as the base SDK.

PR's welcome! ;)

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.0.0-beta.1

`Sentry.isEnabled()`
