### ISSUE TITLE
Fix attachStacktrace on log4j/logback/log4j2

### ISSUE THREAD

**Issue by maciejwalkowiak** [getsentry/sentry-java#897]

**Comment by maciejwalkowiak** [comment]
Attaching stack trace is broken not only for logging framework integrations, but in general stack traces are not attached for SentryEvents that do not have exceptions.

**Comment by marandaneto** [comment]
what is broken? what is the actual and expected behavior? stack traces are added to the thread list if the flag `attachStacktrace` is enabled, see image below, it's a `captureMessage` call without an exception, and all the threads contain stack traces.

![Screenshot 2020-09-04 at 10 10 15](https://user-images.githubusercontent.com/5731772/92216628-d5576100-ee96-11ea-821d-b50d48dd77fe.png)

**Comment by maciejwalkowiak** [comment]
IsAttachStacktrace is passed in SentryOptions constructor to MainEventProcessor. Setters are called at the later stage.

**Comment by marandaneto** [comment]
got it, but when I init the SDK manually and swap the flag, it works, that's interesting.
