### ISSUE TITLE
How to enable the Breakpad backend?

### ISSUE THREAD

**Issue by gawen** [getsentry/sentry-java#915]
Hello,

I plan to use Sentry to report native crashs happening in a Go library embedded in an Android app. Unfortunately I am having poor results with the native unwinder `libunwindstack`.

I've worked with Crashlytics which uses Breakpad to generate a minidump when a crash happens. With such a minidump, I'm able to get a correct stacktrace using the Breakpad's CLI tools or by uploading it manually to Sentry. Therefore I wish to use sentry-android with sentry-native using the Breakpad backend.

How can I do that? I saw that the Breakpad support had been removed and work is being done in a branch to bring it back. If not currently possible, do you plan to support Breakpad in the future?

Thanks! :-)

**Comment by marandaneto** [comment]
sentry-native already has Breakpad support for Android/iOS ootb, not thru this package though.

https://github.com/getsentry/sentry-native/releases/tag/0.4.8

for now, we've decided to keep this package using the inproc backend because of system symbols availability, please use sentry-native directly if you wish to use Breakpad
