### ISSUE TITLE
Configuration for Spring MVC project

### ISSUE THREAD

**Issue by sharif2008** [getsentry/sentry-java#956]
It always looks for **sentry.properties** in desktop in my spring MVC project. It does not work under resource or any other folder. It also does not Sentry.init("dns");

The configuration file sentry.properties (which resolves to absolute path C:\Users\xxx\Desktop\sentry.properties)

**Comment by maciejwalkowiak** [comment]
Since Java SDK 3.0, in Spring integration you can pass `dsn` through:

- `@EnableSentry(dsn="...")` annotation
- environment variable `SENTRY_DSN`
- system property `sentry.dsn`
- or `dsn` property in `sentry.properties` located in the classpath.

Please look into new Spring guide for more details: https://docs.sentry.io/platforms/java/guides/spring/

If you're using Spring Boot, DSN can be set through setting `sentry.dsn` on the `@ConfigurationProperties` class. Look into the guide for more details: https://docs.sentry.io/platforms/java/guides/spring-boot/

Closing, please comment if the issue remains.
